### ISSUE TITLE
Action Blocked after 5 minutes running.

### ISSUE THREAD

**Issue by marciomvm** [alexal1/Insomniac#10]
Any advice?
I also used 2 days ago InstaPy and happened the same. Even with proxy and different ips.

**Comment by GeikoHub** [comment]
used both at the same time ?
(not really same time but period) in this case, maybe Instapy that been detected and not this one.
The script needs some adjustment to be more human for now but after only 5 mins,
i suppose that your account is mark as suspicious for instagram bot.
Wait some days without any run and try again and of course let us know ;)

**Comment by marciomvm** [comment]
Not at the same time. I run with a 1-day difference. I will wait for a few days and I will try again.

Thanks

**Comment by alexal1** [comment]
Thanks for information @jonap339!
Please have look at this answer too https://github.com/alexal1/Insomniac/issues/6#issuecomment-641126725
