### ISSUE TITLE
How to run this in bluestacks?

### ISSUE THREAD

**Issue by sailorbeach** [alexal1/Insomniac#100]
This works well on my android phone, but how can i apply this to an virtual android phone like from bluestacks?

**Comment by philip-ulrich** [comment]
That’s not really a question for a github issue. There is in fact another issue with the same topic though already that you can reference. #84 Really though, you’d be best joining the discord where you can get help from others in the community who are using emulators. It’s very simple however and non of it is specific to this script. 😃

**Comment by gvmturl** [comment]
I will be closing this, feel free to discuss it on #84
