### ISSUE TITLE
ERROR - 'function' object has no attribute 'toBeginning'

### ISSUE THREAD

**Issue by henriqueturl** [alexal1/Insomniac#103]
![Crash-2020-09-06-12-47-17](https://user-images.githubusercontent.com/66460180/92330312-5011af00-f044-11ea-9280-96f8713f898c.png)

![Crash-2020-09-06-13-19-09](https://user-images.githubusercontent.com/66460180/92330316-5142dc00-f044-11ea-88dc-af558317154b.png)

![Crash-2020-09-06-12-16-26](https://user-images.githubusercontent.com/66460180/92330317-5142dc00-f044-11ea-99e4-1fb59968fad9.png)

![Crash-2020-09-06-12-35-47](https://user-images.githubusercontent.com/66460180/92330319-52740900-f044-11ea-9541-1642b9b0ddc2.png)

[log.txt](https://github.com/alexal1/Insomniac/files/5179922/log.txt)
[log2.txt](https://github.com/alexal1/Insomniac/files/5179949/log2.txt)

Getting this error dont know why, thought it was because of the language, but it seems that it is not the case. The script is stopping.

Any ideas?

Thank you.

**Comment by barca0019** [comment]
Have you tried changing the language to English?
