### ISSUE TITLE
Traceback on boot

### ISSUE THREAD

**Issue by GeikoHub** [alexal1/Insomniac#11]
Error on launch.
Vanilla script, no changes.
Brand new launch with new installation today.

![Capture](https://user-images.githubusercontent.com/66672318/84261731-91b1bd00-ab1c-11ea-8988-20b4267be8a8.JPG)

**Comment by alexal1** [comment]
> Remote end closed connection without response

Seems like a problem with the connection, not with the script. Please have a look at #14.
