### ISSUE TITLE
Other bugs that should be fixed.

### ISSUE THREAD

**Issue by SAMXODE** [alexal1/Insomniac#110]
**Thanks for the last bug fixes.**

I have other bugs that should be fixed.

I would like to help you, but I'm a newcomer to programming.

Thanks for all! <3

**This error has occurred three times:**
[Crash-2020-09-13-10-42-37.zip](https://github.com/alexal1/Insomniac/files/5216545/Crash-2020-09-13-10-42-37.zip)

**This error has occurred twice:**
[Crash-2020-09-13-17-19-47.zip](https://github.com/alexal1/Insomniac/files/5216546/Crash-2020-09-13-17-19-47.zip)

**Very often / repeatedly visited profiles / stuck:**
[Crash-2020-09-14-04-27-10.zip](https://github.com/alexal1/Insomniac/files/5216547/Crash-2020-09-14-04-27-10.zip)

**Insomniac using on Setup:**

- Raspberry Pi 3 Model B – Raspberry Pi OS
- Python 3.7
- Android Version 9

**Comment by gvmturl** [comment]
Is it solved?

**Comment by Fadude** [comment]
Please upgrade to v3.6.0, if the bugs is still there, please re-attach crash-zips and reopen.
