### ISSUE TITLE
CRASH - Search bar

### ISSUE THREAD

**Issue by gvmturl** [alexal1/Insomniac#113]
Reporting crash on Action bar
[Crash-2020-09-21-19-38-30.zip](https://github.com/alexal1/Insomniac/files/5258515/Crash-2020-09-21-19-38-30.zip)
[Crash-2020-09-21-19-38-51.zip](https://github.com/alexal1/Insomniac/files/5258516/Crash-2020-09-21-19-38-51.zip)
[Crash-2020-09-21-19-38-08.zip](https://github.com/alexal1/Insomniac/files/5258518/Crash-2020-09-21-19-38-08.zip)

**Comment by alexal1** [comment]
@gvmturl @randinfo if that #114 PR doesn't fix this issue for you, then I'll need `uiautomatorviewer` screenshot. Could you provide one?

**Comment by randinfo** [comment]
How can we provide one to you ?

**Comment by alexal1** [comment]
@randinfo oh wait. I took a deeper look on the problem and I think that I can fix it. Just wait for the next release please.

**Comment by alexal1** [comment]
Please check on `v2.1.7` and close this issue if it's fixed.

**Comment by arthurspa** [comment]
Hi @alexal1, PR #115 automatically adds a dump of the current view hierarchy when a crash occurs.
This way we don't need to ask users to use `uiautomatorviewer` or any other third party tool to provide more information.

**Comment by randinfo** [comment]
@alexal1 yes it's good now

**Comment by gvmturl** [comment]
Solved by 2.1.7, thanks!

Btw when script starts still shows 2.1.6 version
