### ISSUE TITLE
Bot "can't find follow button" error because it has already been requested to follow

### ISSUE THREAD

**Issue by carlos3212345** [alexal1/Insomniac#118]
I've noticed that the bot would sometimes try to follow an IG user that has already been requested and then would try the change the language settings because it couldn't find the follow button after and then it starts following the list again. I think I may have manually requested the user before or the bot did from the last following session but it's kinda time consuming since it goes to settings for no reason. It's not really a major bug but I think it would be a good idea to fix it.

**Comment by alexal1** [comment]
It must work OK already: the script checks "Follow Back" button as well as just "Follow". But in your case it's not working, so it's a bug. Since of `v2.2.5` crashes are saved each time language switching starts. Could you please attach this Crash zip folder here?

**Comment by gvmturl** [comment]
@carlos3212345 is it solved?

**Comment by Fadude** [comment]
Fixed on previuos versions, Should work on v3.5.7
