### ISSUE TITLE
BUG - Followers list scrolling and Iterate over visible followers not end

### ISSUE THREAD

**Issue by guztavoalves** [alexal1/Insomniac#119]
This is a recurring problem.
Eventually the script fails to identify that the list of followers has already ended and so it is 'forever' treating and skipping the same users.

One solution would be to identify if the visible users are the same after scrolling, identifying that the IG is no longer loading new users and has come to an end.

![image](https://user-images.githubusercontent.com/11070237/94837701-f6a26300-03ea-11eb-8b60-6acc5238b15b.png)

**Comment by alexal1** [comment]
Could you give a device screenshot when this happens?

I rely on that there are "recommendations" at the bottom of followers list. But maybe for some accounts you don't have them, then we have to find another criteria of finishing.

**Comment by guztavoalves** [comment]
I see that accounts with few followers have no recommendations at the bottom of the list. 
See the image as it appears.


![image](https://user-images.githubusercontent.com/11070237/94914257-0ec4c180-0481-11eb-9622-e4122fc9a93c.png)

**Comment by alexal1** [comment]
Yes indeed. Ok then I can check that _all_ followers on the screen are the same as on previous screen, and stop if so.

**Comment by guztavoalves** [comment]
Yes, I think that checking this way would solve all the problems with scrolling that list.
