### ISSUE TITLE
swap order of follow & likes

### ISSUE THREAD

**Issue by 10000hzl** [alexal1/Insomniac#120]
I was reading about IG limits on a few sites, and I ran into this bit below, on [this page](https://socialpros.co/instagram-daily-limits#Instagram_Like_limits_in_2020).

`When liking posts, make sure you are liking posts from the accounts you follow, otherwise, you are increasing the chance of getting banned. `

Currently, Insomniac likes a few photos of a user and then follows that user, would it be possible to invert the 2 actions? (follow first, and then like a few photos) Apparently IG prefers this kind of behavior rather than the other way around.

Thanks!

**Comment by alexal1** [comment]
Yes it's possible, but that's strange. Isn't it more "natural" that when you first open someone's profile, you first look at his/her content, like some photos, and if you're impressed, you press follow button? Seems that following anybody you've first seen is more suspicious.

**Comment by alexal1** [comment]
I think the point is that
> make sure you are liking posts from the accounts you follow

so we should add random interactions with our own feed. To give some likes to those whom we follow.

**Comment by Fadude** [comment]
Added on v3.6.0 - 50% randomness of selection an action to be first
