### ISSUE TITLE
I´m, still facing problems showing an error with no user found

### ISSUE THREAD

**Issue by soulpawa** [alexal1/Insomniac#121]
I´m, still facing problems showing an error with no user found
[Crash-2020-10-03-17-47-01.zip](https://github.com/alexal1/Insomniac/files/5322009/Crash-2020-10-03-17-47-01.zip)

<img width="786" alt="Screenshot 2020-10-03 at 17 57 54" src="https://user-images.githubusercontent.com/6342029/94995954-00ba9200-05a2-11eb-92cf-749884355e44.png">

_Originally posted by @soulpawa in https://github.com/alexal1/Insomniac/issues/80#issuecomment-703132408_

**Comment by alexal1** [comment]
According to hierarchy dump, id of button is "com.instagram.android:id/row_profile_header_container_followers" instead of "com.instagram.android:id/row_profile_header_followers_container" as usual 🙄

This can be fixed easily, don't worry :)

**Comment by soulpawa** [comment]
Unfortunately, I'm still getting the same error, :(

<img width="554" alt="Screenshot 2020-10-06 at 22 17 22" src="https://user-images.githubusercontent.com/6342029/95255755-2a81ec00-0822-11eb-8ad8-7f0471a60653.png">
<img width="770" alt="Screenshot 2020-10-06 at 22 17 29" src="https://user-images.githubusercontent.com/6342029/95255767-2ce44600-0822-11eb-93a9-39141ea8a2e9.png">
[Crash-2020-10-06-22-16-46.zip](https://github.com/alexal1/Insomniac/files/5336507/Crash-2020-10-06-22-16-46.zip)

**Comment by alexal1** [comment]
@soulpawa yeah my bad, I'll do another try now.

**Comment by soulpawa** [comment]
still not working for me :(

![Screenshot 2020-10-08 at 13 54 51](https://user-images.githubusercontent.com/6342029/95455270-e3a10d00-096d-11eb-9c62-c1cb8d740f98.png)
![Screenshot 2020-10-08 at 13 53 45](https://user-images.githubusercontent.com/6342029/95455277-e56ad080-096d-11eb-9120-9e0c12a4a068.png)

**Comment by alexal1** [comment]
What happens on the device screen? Does it actually open followers list?

**Comment by soulpawa** [comment]
> What happens on the device screen? Does it actually open followers list?

yes open followers list, I've made a video , maybe it helps

https://streamable.com/ktfhkr

**Comment by alexal1** [comment]
> https://streamable.com/ktfhkr

Cannot open your link, tried in two browsers.
Anyway, better give me a `uiautomatorviewer` screenshot of the screen where it fails. I'll make a tutorial about how to do it and give you a link.

**Comment by soulpawa** [comment]
weird, I can open on my phone and different computers without any problem, maybe it's blocked for your country :/

<img width="847" alt="Screenshot 2020-10-08 at 20 45 31" src="https://user-images.githubusercontent.com/6342029/95500566-419e1680-09a7-11eb-8b14-553e34d2d96e.png">
<img width="920" alt="Screenshot 2020-10-08 at 20 45 22" src="https://user-images.githubusercontent.com/6342029/95500570-4236ad00-09a7-11eb-9940-3a9c2d13aa54.png">

**Comment by alexal1** [comment]
Please make a screenshot of the screen with followers list (where the problem appears) as described here https://github.com/alexal1/Insomniac/wiki/UI-Automator-Viewer:-What-Is-It-And-How-To-Use-It

**Comment by soulpawa** [comment]
> Please make a screenshot of the screen with followers list (where the problem appears) as described here https://github.com/alexal1/Insomniac/wiki/UI-Automator-Viewer:-What-Is-It-And-How-To-Use-It

I'm using raspberry pi, so I guess I won't be able to provide you the "layout hierarchy." :(

**Comment by alexal1** [comment]
It's not necessary to do it on your Raspberri Pi. I guess you have a normal computer too, don't you? The point is to make a screenshot of device/emulator you're using.

**Comment by soulpawa** [comment]
> It's not necessary to do it on your Raspberri Pi. I guess you have a normal computer too, don't you? The point is to make a screenshot of device/emulator you're using.

sorry , I tried for more than 5 hours installing into my mac, and I'm not able to launch automatorviewer, I'm just getting errors, unfortunately it's not just install plug and play, :(

<img width="568" alt="Screenshot 2020-10-10 at 14 21 02" src="https://user-images.githubusercontent.com/6342029/95654940-f9e0d180-0b03-11eb-92a4-915c9bbfee01.png">
ors;

**Comment by soulpawa** [comment]
finally I made it downgrading to 8.0 JDK but I got an error creating a screenshot,

I updated and downgrade SDK and also Java, not able to remove the error unfortunately.

I don't know if it will help

<img width="802" alt="Screenshot 2020-10-10 at 15 12 14" src="https://user-images.githubusercontent.com/6342029/95655951-3a901900-0b0b-11eb-9223-b0b0ecba30ba.png">

[Archive.zip](https://github.com/alexal1/Insomniac/files/5359017/Archive.zip)

**Comment by alexal1** [comment]
Fixed in `v3.1.0`
