### ISSUE TITLE
Unfollow isn't working anymore with new Instagram update

### ISSUE THREAD

**Issue by flodes80** [alexal1/Insomniac#122]
Hi,

The bot can't unfollow anymore since there is a new popup system when you click on "unfollow".
Here is an screenshot and some crash logs

Many thanks for your work btw :) 

![Screenshot_20201004-181113](https://user-images.githubusercontent.com/12677853/95021025-d5ea3f80-066e-11eb-9684-b1374bbee98b.jpg)

[Crash-2020-10-04-01-03-23.zip](https://github.com/alexal1/Insomniac/files/5323594/Crash-2020-10-04-01-03-23.zip)
[Crash-2020-10-04-01-03-34.zip](https://github.com/alexal1/Insomniac/files/5323595/Crash-2020-10-04-01-03-34.zip)
[Crash-2020-10-04-01-03-50.zip](https://github.com/alexal1/Insomniac/files/5323596/Crash-2020-10-04-01-03-50.zip)

**Comment by alexal1** [comment]
@flodes80 strange, the crash happens after popup is shown, but screenshot and hierarchy dump are taken when it's closed. Due to this I cannot debug the problem. Can you run `uiautomatorviewer` and make a screenshot manually with its help?

**Comment by alexal1** [comment]
@flodes80 I made a wiki page, describing how to use `uiautomatorviewer`: https://github.com/alexal1/Insomniac/wiki/UI-Automator-Viewer:-What-Is-It-And-How-To-Use-It.
Could you please make a screenshot of this popup as described in this page?

**Comment by flodes80** [comment]
I'll try to do this asap thanks

**Comment by gvmturl** [comment]
Is it solved?
