### ISSUE TITLE
Bug: Always crashing after "press profile"

### ISSUE THREAD

**Issue by Raidus** [alexal1/Insomniac#124]
Hi,

it always crashes after step "press profile" (profile which will be interacted with).

I have tested different USB Ports and also with Wifi connection. Always crashes at the same step.

**Crash report**
[Crash-2020-10-06-17-24-04.zip](https://github.com/alexal1/Insomniac/files/5334884/Crash-2020-10-06-17-24-04.zip)

OS: MacOS Catalina
Android Debug Bridge version 1.0.41
Mobilephone: Cubot Note 7 (Android 10)

**Comment by Raidus** [comment]
I just tested it with a Huawai P30 (Android 10) and it works perfectly. Seems like the Cubot Note 7 is causing the issues.

**Comment by S85mario** [comment]
@alexal1 I noticed that in the status bar there is no longer the search button and it has been moved up near the direct.. i think "ig" has made a design update

**Comment by S85mario** [comment]
I have the same problem

[Crash-2020-10-06-21-13-57.zip](https://github.com/alexal1/Insomniac/files/5336231/Crash-2020-10-06-21-13-57.zip)

**Comment by alexal1** [comment]
Yes, seems that it's an update. @S85mario could you run latest script version and attach crash again? There is missing hierarchy dump now

**Comment by arthurspa** [comment]
@alexal1 , what do you think of adding the running version somewhere in the crash report?

**Comment by S85mario** [comment]
Ok @alexal1, I update and send you the repoort immediately

**Comment by S85mario** [comment]
@alexal1 now it works correctly, I leave it on for a few hours to be sure...thanks

**Comment by Raidus** [comment]
Oh yeah! I haven't thought about changes in instagram ui. On the Cubot Note 7, where it crashes, instagram version is 162.0.0.42.125.

It cannot find `row_profile_header_followers_container`

https://github.com/alexal1/Insomniac/blob/01c5a63c21b3702c1b85867485c5fd94d806346f/src/action_handle_blogger.py#L67

How can I find the correct selector for this instagram version?

**Comment by alexal1** [comment]
@Raidus this is a duplicate of #121, will be fixes soon.
