### ISSUE TITLE
#125 bis

### ISSUE THREAD

**Issue by mastrolube** [alexal1/Insomniac#126]
Still have the same error
[Crash-2020-10-06-19-04-40.zip](https://github.com/alexal1/Insomniac/files/5335460/Crash-2020-10-06-19-04-40.zip)

**Comment by alexal1** [comment]
> Insomniac v2.2.0

🤔

**Comment by mastrolube** [comment]
I fix it for you but, sorry, I'm not able to create a new pull request.
You will find that inside "New function for turn on/screen that works under windows too #123"

Had to learn that Github, sorry

**Comment by alexal1** [comment]
Seems that is fixed now, isn't it?
