### ISSUE TITLE
Cannot find Follow button (language issue)

### ISSUE THREAD

**Issue by toscan** [alexal1/Insomniac#128]
I just get the last version of the package, and I got this issue which come often. Of course my app is in English.
I checked when exactly the first sentence is displayed, "Cannot find neither Follow button" it's on the profile page and the Follow button exists well so I can confirm it's a bug. :)

When I use again the two weeks ago Insomniac version, it works well again. 

![Sans titre](https://user-images.githubusercontent.com/3525320/95443117-7d5fbe80-095c-11eb-854a-ce8b8e140475.png)

**Comment by toscan** [comment]
I checked when exactly the first sentence is displayed, "Cannot find neither Follow button" it's on the profile page and the Follow button exists well so I can confirm it's a bug. :) 

I got the last Instagram version !

**Comment by alexal1** [comment]
Could you attach a screenshot of the phone screen, please? Maybe there's a bit different text on the button?

**Comment by toscan** [comment]
Since it works with the old version of Insomniac, the issue is not from the device ! (After seing the bug above, I downgraded to the Insomniac previous version and it works well again)

**Comment by toscan** [comment]
I will send you a screenshot of the profil asap, but it's written "follow" as usual, and the bug is present on all profiles.

**Comment by toscan** [comment]
I just noticed you pushed something for debugging my bug. Let me get the new version and get back to you with the information. What do you need me to send you ?

**Comment by alexal1** [comment]
@toscan please send a Crash zip folder of the moment when language switching starts

**Comment by alexal1** [comment]
> After seing the bug above, I downgraded to the Insomniac previous version and it works well again

That's helpful information, I think I know the reason now.

**Comment by muzzol** [comment]
here you are

[Crash-2020-10-08-13-24-27.zip](https://github.com/alexal1/Insomniac/files/5347488/Crash-2020-10-08-13-24-27.zip)

**Comment by alexal1** [comment]
@toscan @muzzol please don't forget to close the issue if the fix works!

**Comment by toscan** [comment]
Yes, you fixed it ! Good job mate
