### ISSUE TITLE
 Is it possible to follow a user's followers?

### ISSUE THREAD

**Issue by jonap339** [alexal1/Insomniac#13]
Hello good afternoon. 
                                    My name is Jonathan, I am from Argentina, I have used Instapy for a long time, but then, when observing that web bots are very detectable, I gave up on the idea and started doing the same job manually using android simulators. (Currently I work with 10 accounts, 2 accounts for each simulator) Looking at your INSOMNE system, I find it very interesting and I am going to test it. Only one thing that I could not visualize in the code, does it have the functionality to follow followers of predefined users?

Thank you very much for your contribution and apologies for my English: p

**Comment by alexal1** [comment]
This feature is coming soon :)
It's in the plan on the main page by the way https://github.com/alexal1/Insomniac#features-in-progress
