### ISSUE TITLE
Crashing during interact-sessions

### ISSUE THREAD

**Issue by kremedved** [alexal1/Insomniac#136]
Environment - HTC One M8
Version - 2.2.7
Parameters:

likes_count: 1
total_likes_limit: 100
repeat: 360
interact - [3-users list]
interactions-count: 28-35
follow-percentage: 30
follow-limit: 50
Crashes attached below:

[Crash-2020-10-11-00-31-52.zip](https://github.com/alexal1/Insomniac/files/5360260/Crash-2020-10-11-00-31-52.zip)

Thanks!

**Comment by alexal1** [comment]
Never seen this before, seems it's an exceptional case and doesn't require a fix. The script restarted after this, didn't it?
<img src="https://user-images.githubusercontent.com/22825859/95666348-56bea500-0b61-11eb-886d-1d2e1d682994.jpg" width="200">

Btw, how did you get such block? Is it only for one post or for all?

**Comment by alexal1** [comment]
That's not a bug, you've specified such "user" yourself

> Action: interact with @brackeysteam, @madewithunity, @unitytechnologies--likes-count, @1

Seems that you forgot to make a space before `--likes-count` 😂
