### ISSUE TITLE
add custom hooks

### ISSUE THREAD

**Issue by muzzol** [alexal1/Insomniac#138]
this is a feature request to add possibility to **execute custom scripts on certain events**.

I was thinking of running Insomniac unnatended but I want to get reports and notifications in case something happens, for example receiving a telegram message.
Instead of hardcode any kind of notification a simpler and efective aproach is executing custom scripts on events like:

- crashes
- session finishes
- new loop (--repeat)

my proposal is that when an event like this occurs it search for a script in src subdir, so if user creates a script like this:

    /opt/Insomniac/src/crash.sh

it gets executed with some specific environment variables or parameters: **date, number of interactions, number of likes, completed sessions, duration, path to crash zip file...**

the script could be of any type: **crash.(sh|py|pl)**
with mentioned example there could be this scripts:

    /opt/Insomniac/src/crash.sh
    /opt/Insomniac/src/finished_session.sh
    /opt/Insomniac/src/new_loop.sh

if no scripts are found, the tool just continues as usual.

**Comment by muzzol** [comment]
I've found another use case: when using emulator, sometime it gets stuck and irresponsive so with a hook I can restart it.

**Comment by muzzol** [comment]
is there any progress on this feature?

**Comment by Fadude** [comment]
Done on v3.6.0

**Comment by muzzol** [comment]
hi, I've found another use case.
sometimes my usb cable got disconnected on my headless setup, and I don't get any info about that as it runs in a raspberry with an attached mobile phone.

can you add on action notifications?

in my proposal I suggested simple names for script hooks that get executed if found.
so in this case it would be something like

      $INSOMNIAC_DIR/no_devices.sh

or maybe a generic error script hook would be enough. something like

      $INSOMNIAC_DIR/error.sh

this way I can send a notification or execute whatever I want on each action.

what do you think?
