### ISSUE TITLE
Crashing during interact-sessions

### ISSUE THREAD

**Issue by kremedved** [alexal1/Insomniac#141]
Environment - HTC One M8
Version - 2.2.8
Parameters:

likes_count: 1
total_likes_limit: 100
repeat: 360
interact - [3-users list]
interactions-count: 28-35
follow-percentage: 30
follow-limit: 50
Crashes attached below (copied text from console, because it didn’t save it into the archive or to the folder):

[insomniac.log](https://github.com/alexal1/Insomniac/files/5385139/insomniac.log)

**Comment by Fadude** [comment]
Please upgrade to v3.6.0. If the bug is still there, please reopen.
