### ISSUE TITLE
Crashing while getting Follower List

### ISSUE THREAD

**Issue by Palestar2700** [alexal1/Insomniac#142]
Trying to get Insomniac up and running on a new phone. I already have a working setup with a different Android phone, but wanted to start another bot for a new IG account. Tried the same setup as before, but getting an error as soon as it tries to pull the follower lists.

Seems to work fine up until that point, but I can't actually get a list of followers without it crashing.

I've attached an error screenshot

<img width="1511" alt="Screen Shot 2020-10-15 at 5 34 57 PM" src="https://user-images.githubusercontent.com/72953224/96199713-00f54e80-0f0d-11eb-82d7-a1f2d21beea4.png">

**Comment by soulpawa** [comment]
I'm having the same problem with one phone, :( it will be nice if you can attach your crash, to help developers to detect /find / solve the issue!

**Comment by Palestar2700** [comment]
I attached the Crash log, is there something else I'm supposed to be posting?

**Comment by Palestar2700** [comment]
Just wanted to say problem fixed with an update to newest 1.8.4

Running much faster as well with the uiautomator-v2!
