### ISSUE TITLE
Put close_instagram(device_id) at the end of the main class

### ISSUE THREAD

**Issue by Cangarw** [alexal1/Insomniac#144]
I had sometimes the problem that Instagram did some random pop up or similar things that made the script crash.

While crashing, the script leaves the app open on the phone. This opened app could probably trigger the bot detection from Instagram.

Could you just put a `close_instagram(device_id)` at the end of the main function?
This solved the issue for me. And at the next start there will be a freshly opened Instagram app. 👍

**Comment by Fadude** [comment]
Will be added the next release (v3.4.1)
