### ISSUE TITLE
Cannot auto-run with cron

### ISSUE THREAD

**Issue by sepi2048** [alexal1/Insomniac#147]
Hi,
I made this simple bash script (run-insta.sh) that should run insomniac every 8 hour:

```
#!/bin/sh
    
/usr/bin/python3 /home/me/Insomniac/insomniac.py --interact <user1> <user2> <user3> --total-likes-limit 150 --follow-percentage 10
```
In sudo crontab -e:

`0 */8 * * * /bin/bash /home/me/Insomniac/run-insta.sh
`

The bash script seem to be fired every 8 hour, but not run properly. This is my cron log output

```
[10/20 18:07:02] Connected devices via adb: 1. That's ok.
[10/20 18:07:02] Instagram version: not found
[10/20 18:07:02] Using uiautomator v2
[10/20 18:07:02] Please install uiautomator2: pip3 install uiautomator2
```

Have anyone made insomanic to run by the help of cron or in any other way?

P.S. This run-insta.sh bash script runs flawless when executed manualy

**Comment by darmawan07** [comment]
Try with this. 

#!/bin/bash
    
python3 /home/me/Insomniac/insomniac.py --interact <user1> <user2> <user3> --total-likes-limit 150 --follow-percentage 10

**Comment by Foncekar** [comment]
Just run this `pip3 install uiautomator2`

**Comment by sepi2048** [comment]
> Just run this `pip3 install uiautomator2`

I obviously has `uiautomator2` installed if the bash script run successfully when executed manually. There seems to be a path issue reflated to `uiautomator2` when it tries to run through cron.
