### ISSUE TITLE
FEATURE - Backup for interacted_users.json

### ISSUE THREAD

**Issue by guztavoalves** [alexal1/Insomniac#148]
I had an problem with this file many times, the content is blank after script crash or error when try writing on disk.

This file is very important, then creating an backup every new session resolve this problem.

Every new session get the content of interacted_users.json if not Null save the content in interacted_users_backup.json, after finished the session or script finished, save the content in interacted_users.json and interacted_users_backup.json.

I updated the storage.py for this feature, that's working fine. =)

[storage.zip](https://github.com/alexal1/Insomniac/files/5417564/storage.zip)

**Comment by Fadude** [comment]
Everything is under a sqlite3 db. Is it still needed?
