### ISSUE TITLE
v3.0.0 Crashing :(

### ISSUE THREAD

**Issue by cecimascaras** [alexal1/Insomniac#154]
[Crash-2020-10-27-10-50-58.zip](https://github.com/alexal1/Insomniac/files/5446053/Crash-2020-10-27-10-50-58.zip)

![Capturar](https://user-images.githubusercontent.com/73065665/97317689-d16a0e80-1849-11eb-9b09-25076b4113c4.PNG)

**Comment by alexal1** [comment]
Fixed in `v3.1.0`
