### ISSUE TITLE
PyPI installation problems

### ISSUE THREAD

**Issue by quintendewilde** [alexal1/Insomniac#155]
I have this installation issue with raspberry pi and the Pypi installation.

  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-43z4cc54/pendulum/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-43z4cc54/pendulum/

**Comment by fp231** [comment]
Same here.

**Comment by alexal1** [comment]
You should update your `pip`:
```
python3 -m pip install pip --upgrade
```
