### ISSUE TITLE
No attribute run

### ISSUE THREAD

**Issue by quintendewilde** [alexal1/Insomniac#157]
I get this following error after installation of the new PyPi packages.

Traceback (most recent call last):
  File "start.py", line 4, in <module>
    insomniac.run(activation_code)
AttributeError: module 'insomniac' has no attribute 'run'

**Comment by alexal1** [comment]
This is most likely because there's insomniac.py file in the same directory as start.py. You should remove insomniac.py because names of the file and the package are conflicting.
