### ISSUE TITLE
Please Add A License

### ISSUE THREAD

**Issue by philip-ulrich** [alexal1/Insomniac#159]
Presently there is no license on the code. Due to recent changes, myself and others that were actively writing code for this project are not very pleased. The way that the project is being monetized while removing it's open source is leaving us between a rock and a hard place. Since it has [no license](https://choosealicense.com/no-permission/), it cannot be forked off and spun off into a new project. I'm requesting that you add a license to v2 of the project so that myself as well as other developers can maintain a proper free and open source version based off of v2.

Might I recommend the [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) or even better [MIT](https://choosealicense.com/licenses/mit/).

**Comment by arthurspa** [comment]
I agree. I also would like to continue contributing for an open source version.

**Comment by GitNees** [comment]
That would be great!

**Comment by philip-ulrich** [comment]
Thank you. :)
