### ISSUE TITLE
Raspbian support?

### ISSUE THREAD

**Issue by pezzotto** [alexal1/Insomniac#16]
Hi, I want to try this script on mi RpiB3+ but I’m unable to find any androidsdk working on armhf.

Anyone have installed the android platform tools on raspberry pi?

Thanks 

EDIT: I’ve installed android-tools-adb and android-tools-fastboot, adb server started so I will try to connect a phone asap and see if device will be recognized.

**Comment by alexal1** [comment]
Maybe @GabrieleAnsaldo can help you, nobody else didn't work with Raspberri Pi as I know.

**Comment by pezzotto** [comment]
I can confirm that it’s working but on android 5.0.2 I have no interactions as the bug marked issue.

**Comment by gvmturl** [comment]
@pezzotto are you using raspbian?

Just tried on Ubuntu mate w/o success...

Asking for key... I ll try to check what is it? Any idea?

**Comment by GabrieleAnsaldo** [comment]
Did you manage to fix the issue with the Raspberry? @pezzotto

**Comment by gvmturl** [comment]
@GabrieleAnsaldo Arent you using a Raspberry?

**Comment by pezzotto** [comment]
> Did you manage to fix the issue with the Raspberry? @pezzotto

Yes i've simply installed android-tools-adb and android-tools-fastboot and adb recognize my device.

Thanks

**Comment by pezzotto** [comment]
> @pezzotto are you using raspbian?
> 
> Just tried on Ubuntu mate w/o success...
> 
> Getting unauthorized... I ll try to check what is it? Any idea?

You must authorize by clicking on the popup on the phone first time you launch adb shell

**Comment by gvmturl** [comment]
I created by myself a folder into user/.android to get non authorized device. If I delete this folder and try to adb devices it says that key don’t exists 

![image](https://user-images.githubusercontent.com/52518293/84544000-d4b59100-acd2-11ea-84d5-3aadd200f13d.jpeg)


On Windows I don’t have this issue...

**Comment by pezzotto** [comment]
@gvmturl on raspbian I just installed android-tools-adb and android-tools-fastboot, not the sdk because it’s not supported on raspberry pi.

You should try to reinstall the sdk, also take a look here: https://stackoverflow.com/questions/32132434/set-adb-vendor-keys/33768414#33768414

**Comment by gvmturl** [comment]
As steps are on README.md i will be closing this issue, because, yes Insomniac supports Raspberry Pi OS.
