### ISSUE TITLE
Hashtag Support

### ISSUE THREAD

**Issue by philip-ulrich** [alexal1/Insomniac#160]
Related to the changes in v3, it was originally said this would be included in the free version. You can find the statement here: https://discord.com/channels/738695604955250739/738716094256381983/744582770935857184. Given that the project is no longer open source, I do not wish to use it any longer, but you should give to the other users of the project the feature that was told they would be given.

**Comment by alexal1** [comment]
You're right, I will consider making it free in the next update. Thanks for your caring!

**Comment by alexal1** [comment]
Hashtags made free since of `v3.1.0`.
