### ISSUE TITLE
User name not found error

### ISSUE THREAD

**Issue by noisyninjafeet** [alexal1/Insomniac#161]
I have updated to latest code and I continue to get the user name not found error upon initialization. The script will run but the previously interacted users list will not be used.

**Comment by alexal1** [comment]
Well seems that your UI is slightly different, that's why the script cannot find your username. Here's the plan:

1. Wait for next release (today or tomorrow): I will save crash on each username not found error
2. Attach this crash here
3. I will fix the script using crash info

**Comment by arthurspa** [comment]
Hi, if anyone is interested in a fix for this, please use this commit:

We have a fix for that: https://github.com/GramAddict/gramaddict-bot/commit/6d4873b8ba60409628a8fb6ba2dbf25676ef288a

**Comment by alexal1** [comment]
I will reopen it because it's still not fixed in insomniac, ok?

**Comment by alexal1** [comment]
Fixed in `v3.1.0`
