### ISSUE TITLE
Illegal character (d83c)

### ISSUE THREAD

**Issue by Foncekar** [alexal1/Insomniac#166]
I have encountered this error several times since some time, if I relaunch it may be that I encounter or not the worry. I think there’s a good lead with the "Illegal character (d83c)"

[error.txt](https://github.com/alexal1/Insomniac/files/5470617/error.txt)

**Comment by zubus** [comment]
Hey! Try [GramAddict](https://github.com/GramAddict/bot) better fork of insomniac, full open source and free ;)
Ps and without bugs :P
