### ISSUE TITLE
Can't unfollow non-followers

### ISSUE THREAD

**Issue by bronzeboy** [alexal1/Insomniac#167]
The bot skin anyone becasue can't get follow status

` Skip @xxx. Following status: NONE.`

**Comment by bronzeboy** [comment]
My bad, can only unfollow who bot followed, should be nice having an option to unfollow even others if they not follow you back

**Comment by alexal1** [comment]
@bronzeboy use `--unfollow-any` and if there are users who you don't want to be unfollowed, add them to the `whitelist.txt` (https://github.com/alexal1/Insomniac#whitelist-and-blacklist)

**Comment by bronzeboy** [comment]
> @bronzeboy use `--unfollow-any` and if there are users who you don't want to be unfollowed, add them to the `whitelist.txt` (https://github.com/alexal1/Insomniac#whitelist-and-blacklist)

I could be nice to have just a --unfollow-any-non-follower like instapy does, just check if the account dosen't follow you back no matter who followed it!
