### ISSUE TITLE
Hashtag support works different then expected.

### ISSUE THREAD

**Issue by GitNees** [alexal1/Insomniac#172]
As I tried it out now, I expected usage like InstaPy, where when you search a hashtag, it goes to recent.Till there, all good, but then it doesn't like the pictures with those tags. It goes to the users that liked the picture. I understand the logic behind that.

But the other option is something I would like to see, as this really helps in certain branches, as you want to interact with users in the same branch.
Now it will go to users that liked a certain picture. This function is also not bad at all and usefull also, but liking pictures and following the user that posted a pic with that hashtag, it also a great value.

This is how I made my account grow quickly when I used instapy long time ago.

Since with hastags, you mostly like pictures that are recently posted, they will also notice you quicker, as users most of the time check their progress on likes and who... That way, they come look on your page also.

Is this something that is still in the pipeline?

Because now it likes pictures totally not related to the hashtag, as it digs to deep... 

An example would be; you look for a certain hashtag to find a certain model that also  did some shoots in that branch. That way you interact with the correct person, they might check your profile, like your work and follow you. Now it doesnt follow and interact with the model. It interacts with the people that like the picture.

**Comment by alexal1** [comment]
> Is this something that is still in the pipeline?

Yes. Right now @Fadude is making a huge refactoring of the code. It will make the code more "modular" and it will make it easier to add more "feature modules" leaving core code the same. We believe that after this refactoring we'll be able to create features much faster; also it will become easy for other contributors.

**Comment by GitNees** [comment]
I hope, as for this is now a weird interaction. It might like pictures that are old from a user instead of the recent posted with that hashtag totally non related.

**Comment by Moein-9** [comment]
@alexal1  Any update on this functionality?   I really would love to see this functionality comes to live.

**Comment by Fadude** [comment]
@Moein-9 We are working really hard to deliver it ASAP :) few more days and a new version will be released

**Comment by Moein-9** [comment]
> @Moein-9 We are working really hard to deliver it ASAP :) few more days and a new version will be released

looking forward to it! thanks for the quick reply!

**Comment by simonmannsfeld** [comment]
@Fadude issue closed? Is the feature live now? Would love to use it! Great work!
