### ISSUE TITLE
3.1.2 - ImportError: cannot import name 'switch_to_english' from 'insomniac.navigation' (C:\Python\lib\site-packages\insomniac\navigation.py)

### ISSUE THREAD

**Issue by GitNees** [alexal1/Insomniac#174]
Just updated as test, lucky I could go back.

Crashes immediatly, whule 3.1.1 worked.

ImportError: cannot import name 'switch_to_english' from 'insomniac.navigation' (C:\Python\lib\site-packages\insomniac\navigation.py)

**Comment by alexal1** [comment]
Strange, just checked that works fine on my computer. Could you attach the full log?

**Comment by Fadude** [comment]
Please update to v3.6.0
