### ISSUE TITLE
Error after 2nd round 

### ISSUE THREAD

**Issue by toscan** [alexal1/Insomniac#176]
<img width="1043" alt="Screenshot 2020-11-05 at 18 02 59" src="https://user-images.githubusercontent.com/3525320/98276565-6f6e7f00-1f96-11eb-945e-1f3ae0286449.png">

And the crash file :  
[Crash-2020-11-05-16-55-25.zip](https://github.com/alexal1/Insomniac/files/5496059/Crash-2020-11-05-16-55-25.zip)

**Comment by gvmturl** [comment]
#173

**Comment by toscan** [comment]
Oh yes thanks, the fix will be in the next release ?

**Comment by GitNees** [comment]
Read post 173 and read my solution, you can run it with extra parameter yourself

**Comment by Fadude** [comment]
Fixed on v.3.3.2, closing.
