### ISSUE TITLE
Crash on following of account with shop

### ISSUE THREAD

**Issue by toscan** [alexal1/Insomniac#177]
I don't understand what's happening... It happens sometimes without any reason.

[Crash-2020-11-05-23-54-13.zip](https://github.com/alexal1/Insomniac/files/5499841/Crash-2020-11-05-23-54-13.zip)
<img width="954" alt="Screenshot 2020-11-06 at 08 52 59" src="https://user-images.githubusercontent.com/3525320/98340360-88664700-200d-11eb-859d-4cdad8a6b519.png">

**Comment by toscan** [comment]
Related to : https://github.com/alexal1/Insomniac/issues/146

**Comment by Fadude** [comment]
Fixed on v3.4.0 - added shop-profile support
