### ISSUE TITLE
Following status: NONE on interacted users

### ISSUE THREAD

**Issue by 10000hzl** [alexal1/Insomniac#181]
Hi, I noticed that in recent days Insomniac is assigning **Following status: NONE** to users that were followed by Insomniac.
This is a problem because when I run unfollow sessions, these users aren't unfollower.
Why is this happening? (version 3.0.0)

Many thanks

**Comment by pixelicous** [comment]
same here, but as i understood this it skipped as it already checked their unfollow status

**Comment by Fadude** [comment]
Thanks for the issue-submission, under investigation, a bugfix will be release soon

**Comment by Fadude** [comment]
Should be fixed on v3.6.0, please re open if still happening
