### ISSUE TITLE
Can't start iuautomator-v2

### ISSUE THREAD

**Issue by Gabyheavy** [alexal1/Insomniac#183]
Caught an exception while starting iuautomator-v2

Not sure what to do I followed get started page

![image](https://user-images.githubusercontent.com/20093115/99260284-78274680-281b-11eb-9053-f7da0d16b1ad.png)

**Comment by Gabyheavy** [comment]
Tried to run the command for more infos
![image](https://user-images.githubusercontent.com/20093115/99260904-4b276380-281c-11eb-8e2e-e2ab55ef2780.png)

**Comment by alexal1** [comment]
@Gabyheavy `uiautomator2` doesn't support all devices, so try to run the script with the `--old` flag. It's a fallback to the first version of uiautomator.

**Comment by Gabyheavy** [comment]
Exactly same errors it tries to run uiautomator2 nevertheless

**Comment by Gabyheavy** [comment]
Ok not using config file and using command flags worked

**Comment by alexal1** [comment]
Yes you're right that's a bug. Will be fixed in next release, thanks!

**Comment by Fadude** [comment]
@Gabyheavy Using old param in the config file didnt helped?

**Comment by Fadude** [comment]
Fixed on v.3.3.1, closing.
