### ISSUE TITLE
Nothing happens using starter and --old

### ISSUE THREAD

**Issue by Gabyheavy** [alexal1/Insomniac#184]
I am using the get started commands along with --old and the script does not seem to do anything except opening the app.

![image](https://user-images.githubusercontent.com/20093115/99272406-0e616980-2828-11eb-8312-86228d07fa0b.png)

**Comment by alexal1** [comment]
Oh probably Instagram has a bit different UI on your device. Here are possible solutions:
- Use emulator. I've written instructions for [Windows](https://www.patreon.com/posts/how-to-install-43543116) and [macOS/Linux](https://www.patreon.com/posts/how-to-install-43485861)
- Make a **UI Automator Viewer** screenshot of Instagram on your device and attach to this issue. [Here](https://github.com/alexal1/Insomniac/wiki/UI-Automator-Viewer:-What-Is-It-And-How-To-Use-It) is the instruction of how to use this tool.

**Comment by Fadude** [comment]
Fixed on v.3.3.1, closing.
