### ISSUE TITLE
error: argument --interact: expected at least one argument

### ISSUE THREAD

**Issue by 10000hzl** [alexal1/Insomniac#185]
I don't understand what I'm doing wrong. 3.2.0 only interacts by hashtag and doesn't let me interact by username.
I tired with the [interact.json](https://raw.githubusercontent.com/alexal1/Insomniac/master/config-examples/interact.json) file in the readme too, and the same thing happens.

![image](https://user-images.githubusercontent.com/29522006/99289762-ae75bd80-283d-11eb-9107-63834aaa89fb.png)

**Comment by Fadude** [comment]
Hi,
You are using powershell, and @ symbol has specific usage in powershell.
Try run the command in regular cmd windows.

See also:
https://stackoverflow.com/questions/363884/what-does-the-symbol-do-in-powershell
