### ISSUE TITLE
v3.2.0 not working: 32002 Client error:

### ISSUE THREAD

**Issue by sepi2048** [alexal1/Insomniac#188]
So I tried to install v3.2.0 after using v2.2.8 successfully for a while on my Ubuntu 20.04.

After `python3 -m pip install insomniac`
I added `start.py `to a new folder, made it executable with `chmod +x`.

I ran the command: 
python3 start.py --interact @account --follow-percentage 15 --total-likes-limit 150 --device 11111

The app on the device never opens on the device and this is the exception I get:

`Caught an exception:
-32002 Client error: <> data: Selector [childOrSibling=['child'], childOrSiblingSelector=[{'mask': 8388608, 'childOrSibling': [], 'childOrSiblingSelector': [], 'index': 4}], resourceId='com.instagram.android:id/tab_bar', className='android.widget.LinearLayout'], method: None`

I tried to updated the Android platform tools from 30.0.4 to 30.0.5. 
(The v2.2.8 still works from a separate folder.)

Please help!

**Comment by moritz-fenske** [comment]
I have the same issue but it works for me if I have the app active and not closed. But still it does not work if we use the repeat argument because then the app is in the background.

**Comment by Sejdra-ing** [comment]
in the  **session.py** file you can comment out the following line: 
change 
        close_instagram(device_wrapper.device_id)
to 
        # close_instagram(device_wrapper.device_id)

that solves the problem while waiting for the fix of this bug in the next version.

**Comment by herbertgroff** [comment]
Same error here, workaround doesnt help but throws new error ;(

**Comment by 0libar** [comment]
As strange as it sounds a simple closing/reopenning the app worked for me...

**Comment by Fadude** [comment]
Fixed on v.3.3.2, closing.
