### ISSUE TITLE
follow-percentage argument not working

### ISSUE THREAD

**Issue by moritz-fenske** [alexal1/Insomniac#189]
I have set the follow-percentage argument to 50 but it does not follow anyone.

I am using version 3.3
and I executed following command:
`python3 start.py --interact @natgeo --follow-percentage 50 --device XY`

**Comment by EdenANNONAY** [comment]
Same here and it happened just after I installed the new version @alexal1

**Comment by Fadude** [comment]
Under investigation, a bugfix will be release soon

**Comment by EdenANNONAY** [comment]
Thanks, so far reverting to v3.1.2 seems to work just  fine :)

> python3 -m pip uninstall insomniac
> python3 -m pip install insomniac==3.1.2

**Comment by cecimascaras** [comment]
thanks, the downgrade worked 👍 

adb with two devices returned to work

**Comment by Fadude** [comment]
Fixed on 3.3.1
