### ISSUE TITLE
Script travelling

### ISSUE THREAD

**Issue by GeikoHub** [alexal1/Insomniac#19]
Impossible to show the bug, it only appears on the phone screen but not on the cmd.

randomly, it goes on the phone galerie. 
(even one time on my own profile, i can suppose that is "normal" to make a more human interaction like said in the notice)
I suppose that it's press the wrong key,
(the "+" instead of "back" or "search" key)
the script continue as nothing happens but the phone is totally elsewhere than it should be...
maybe resolution of the screen is different as it suppose to be in the script?

**Comment by gvmturl** [comment]
Could you please try to record the action?

**Comment by GeikoHub** [comment]
not easy cause it needs to be a video record of the phone screen to really see what happen.
And in fact, it appear ramdomly, so need to check every seconds and start record when happen ^^"

By the way, you'll don't see more than the phone trying to like and goes into gallery ("+" key) 
Then it act without any sens until press the back button of the script to get back on follower list.

I didn't let it make all the action to prevent a wrong post...

**Comment by gvmturl** [comment]
> not easy cause it needs to be a video record of the phone screen to really see what happen.
> And in fact, it appear ramdomly, so need to check every seconds and start record when happen ^^"
> 
> By the way, you'll don't see more than the phone trying to like and goes into gallery ("+" key)
> Then it act without any sens until press the back button of the script to get back on follower list.
> 
> I didn't let it make all the action to prevent a wrong post...

Don t android has the option record screen by default?

**Comment by GeikoHub** [comment]
not on this old one....
Have that just happened but only screenshots, don't think it'll really help but nothing better at this time

![IMG_20200613_130708__01](https://user-images.githubusercontent.com/66672318/84567331-3e3bab00-ad78-11ea-8dba-7507e4a5ffdf.jpg)
![IMG_20200613_130717__01](https://user-images.githubusercontent.com/66672318/84567332-3f6cd800-ad78-11ea-8ec9-e1ab892163c9.jpg)

**Comment by gvmturl** [comment]
Any app for recording screen?

What is the exactly message on terminal when it opens gallery? Try to catch.

**Comment by GeikoHub** [comment]
Not enought space or memory to launch/install any other app...
(uninstall everything just to can install insta)
But not seems to make this bug with another phone (my more recent one i mean)

And i don't saw any "precise" thing.
Just as a "miss click" that put in gallery instead of liking a pic.
Was for that reason that i said this maybe cause by the resolution of the screen (to make understandable for you).

**Comment by GeikoHub** [comment]
now it did that after get on gallery

![Capture](https://user-images.githubusercontent.com/66672318/84568095-68dc3280-ad7d-11ea-8e48-fc347e5d03e7.JPG)

**Comment by gvmturl** [comment]
> now it did that after get on gallery
> 
> 
> 
> ![Capture](https://user-images.githubusercontent.com/66672318/84568095-68dc3280-ad7d-11ea-8e48-fc347e5d03e7.JPG)
> 
> 

#21

**Comment by GeikoHub** [comment]
all right!
Sorry you're already on it so ;)

**Comment by gvmturl** [comment]
> all right!
> 
> Sorry you're already on it so ;)

In my case it seems to happens when open a IGTV video.... then restart ig and script... i think that it’s a way found to solve “IGTV BUG” not sure. is it not the same for you?

Thank you.

**Comment by GeikoHub** [comment]
Don't know if it always appear when opening IGTV but yes i've seen this too.
And you're right, it's restarting IG and the script when happen

**Comment by gvmturl** [comment]
> Don't know if it always appear when opening IGTV but yes i've seen this too.
> 
> And you're right, it's restarting IG and the script when happen

Let’s keep observing it and waiting a solution for handling  this error message.

Thanks for sharing your experiences.

**Comment by alexal1** [comment]
I had similar bug, but in my case in was accidental press on Back arrow in profile instead of Like button. Explanation was quite funny – Like button sometimes appeared to be right below the Back arrow.

Can't the same happen in your case? Is it possible that Like button is exactly under the "+" button?

**Comment by jonap339** [comment]
The exact same thing happened to me. I'm going to run again and if I can detect it, I pass the data. @alexal1 , what do you need me to attach when I detect this problem?

**Comment by alexal1** [comment]
@jonap339 
> The exact same thing happened to me

Do you mean unexpected backpress? I thought I've fixed this bug finally...
Well, I think screenshots of the state where it happens can help.

**Comment by jonap339** [comment]
After the update I have not seen it anymore! Excellent !!

**Comment by gvmturl** [comment]
Is it solved? @GeikoHub

**Comment by gvmturl** [comment]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 438, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 135, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.LinearLayout, RESOURCE_ID=com.instagram.android:id/row_profile_header_followers_container]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insomniac.py", line 91, in _job_handle_bloggers
    handle_blogger(device, blogger, likes_count, storage, _on_like, on_interaction)
  File "/home/pi/Insomniac/action_handle_blogger.py", line 17, in handle_blogger
    _open_user_followers(device, username)
  File "/home/pi/Insomniac/action_handle_blogger.py", line 39, in _open_user_followers
    followers_button.click.wait()
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 76, in __call__
    return self.func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 975, in _click
    return self.jsonrpc.clickAndWaitForNewWindow(self.selector, timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 458, in wrapper
    return _method_obj(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/uiautomator/__init__.py", line 135, in __call__
    "%s: %s" % (jsonresult["error"]["data"]["exceptionTypeName"], jsonresult["error"]["message"])
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.LinearLayout, RESOURCE_ID=com.instagram.android:id/row_profile_header_followers_container]

**Comment by GeikoHub** [comment]
the problem appeared to be solved until yesterday, 
i had the problem back but haven't screenshot the traceback,
i'll report it when i'll see it again!

**Comment by alexal1** [comment]
@gvmturl @GeikoHub probably fixed, fill free to reopen if appears. But in that case attach stacktrace and screenshot, please.
