### ISSUE TITLE
Crash at the end of an interact session

### ISSUE THREAD

**Issue by Sc0l10** [alexal1/Insomniac#190]
[Crash-2020-11-19-12-56-27.zip](https://github.com/alexal1/Insomniac/files/5566779/Crash-2020-11-19-12-56-27.zip)

**Comment by zubus** [comment]
Hey! Try [GramAddict](https://github.com/GramAddict/bot) better fork of insomniac, full open source and free ;)
Ps and without bugs :P

**Comment by Fadude** [comment]
Fixed on v3.5.0
