### ISSUE TITLE
Can't confirm unfollow on private account

### ISSUE THREAD

**Issue by flodes80** [alexal1/Insomniac#193]
Hi,

Insomniac is not able to unfollow private account when it shows a dialog to confirm unfollow of private account.

See crash file.

Thanks
[Crash-2020-11-21-01-00-47.zip](https://github.com/alexal1/Insomniac/files/5577337/Crash-2020-11-21-01-00-47.zip)

**Comment by alexal1** [comment]
Yeah, known problem, will be fixed in the next release

**Comment by Fadude** [comment]
Fixed on v.3.3.2, closing.

**Comment by evertonmdz** [comment]
Same bug here...
