### ISSUE TITLE
Getting soft bans extremely quickly from repeated actions

### ISSUE THREAD

**Issue by adchsm** [alexal1/Insomniac#198]
Hey there,

I'm currently on a soft ban: 'limit number of interactions to protect community' and have been for approx 24 hours so far.

I received the ban after following approximately 30 users from a pre-scraped targets.txt file (that I had obtained from a separate account and separate device).

Each session followed a range of 9-11 users with a 60-75 minute break in between each session, by the fourth session I was banned.

I think the error is related to this: https://github.com/alexal1/Insomniac/issues/177

The bot can't seem to find the follow button on accounts that have a shop, and it heads to the settings, checks the language is English, heads back to the target user, can't find the follow button again, repeats, and gets stuck in this loop.

It seems Instagram is detecting the repeated profile visits, settings visits or language change attempts and placing bans on accounts.

It's also worth noting that my scraper has filters set up to skip business accounts, but some accounts with shops still seem to slip through.

Any help you could provide would be amazing and very much appreciate!

Thanks for building a fantastic tool!

**Comment by Fadude** [comment]
Hi @adchsm, shops pages interaction will be available on next release. Stay tuned :)

**Comment by adchsm** [comment]
That's fantastic news, thank you!
