### ISSUE TITLE
Send Dm/comment

### ISSUE THREAD

**Issue by GeikoHub** [alexal1/Insomniac#20]
Again, more a request but haven't capacity to program it.

Something like;
if no post, 1/2 post, or if private account > send "private message" (to reach inaccessible account)
randomly send > "private message"
randomly > post "comment"

**Comment by gvmturl** [comment]
Mentioned this issue into #18 that is also discussing scripts implementations.

I will be closing this issue to concentrate discussion there, feel free to reopen it anytime if your request is not met.
