### ISSUE TITLE
'SessionState' object has no attribute 'sum'

### ISSUE THREAD

**Issue by anto582** [alexal1/Insomniac#200]
Ver 3.4.0
Caught an exception:
'SessionState' object has no attribute 'sum'
[Crash-2020-11-29-12-28-49.zip](https://github.com/alexal1/Insomniac/files/5612636/Crash-2020-11-29-12-28-49.zip)

**Comment by Fadude** [comment]
Thanks, we have found the bug and a hotfix will be released soon
