### ISSUE TITLE
Interacts with the same people over and over

### ISSUE THREAD

**Issue by stadtblick** [alexal1/Insomniac#203]
The script keeps interacting with the same people over and over again. Sometimes it even starts interacting with my own posts. In the end this looks like very spammy behavior.
Am I doing something wrong or is this a bug?

**Comment by zubus** [comment]
Hey! Try [GramAddict](https://github.com/GramAddict/bot) a better fork of insomniac, full open source and free ;)

**Comment by jduhautois** [comment]
Agreed, the bot interacts with users it already with interacted before. The users can be found in the interacted_users.json file under my profile. I wonder if there is a way to prevent that from happening.

**Comment by Fadude** [comment]
Can you share your bot-params and log with us?

**Comment by jduhautois** [comment]
Mmmh I was experiencing a similar issue and I notice that there's a big whole in my interacted_users.json file between July and November. 
I think November is when I updated Insomniac for the first time in a while.
@stadtblick what do your interacted_users.json file look like? Are you using the latest version of Insomniac?

**Comment by stadtblick** [comment]
Just checked interacted_users.json and it hasn't logged anything since 2020-11-12. Probably around the same time the script stopped being able to read my username on my profile.
I'm using the most recent version but now have switched to a different script that works much better.
