### ISSUE TITLE
Follow script doesn't follow

### ISSUE THREAD

**Issue by jduhautois** [alexal1/Insomniac#204]
I run this script and it interacts with users & likes pictures successfully, but it doesn't follow. It used to work but no longer does. Any idea what I am doing wrong?

python start.py --interact @handle-followers --interactions-count 50-100 --likes-count 1-3 --follow-percentage 90 --repeat 30-80  --no-speed-check

**Comment by Fadude** [comment]
Can you send a session log please? is it still happening on version 3.6.0?

**Comment by fp231** [comment]
Hi. I have the same issue on version 3.6.8. Sent a logfile with it. I tried different settings and filterings, but it just doesn't follow anymore...

[insomniac_log-2021-02-16-08-45-09.log](https://github.com/alexal1/Insomniac/files/5989530/insomniac_log-2021-02-16-08-45-09.log)

**Comment by fp231** [comment]
To clear things up. I got to work again by using another .json. I think on parameter
/filter needs to be set for the script to use follow. Would be happy to hear what was causing this...

**Comment by jduhautois** [comment]
It was a while back but I think I had gotten past it by increasing the total follow limit.
