### ISSUE TITLE
Expecting property name enclosed in double quotes: line 42328 column 9 (char 1310851)

### ISSUE THREAD

**Issue by anto582** [alexal1/Insomniac#206]
Hi

When I use a dummy account the script works fine, but when I use the target account (@brazolovers) I have this error

Caught an exception:
Expecting property name enclosed in double quotes: line 42328 column 9 (char 1310851)

[Crash-2020-12-04-20-50-43.zip](https://github.com/alexal1/Insomniac/files/5646299/Crash-2020-12-04-20-50-43.zip)

**Comment by anto582** [comment]
I already found the problem, the interacted_users.json file was corrupt

**Comment by alexal1** [comment]
Well my current task is to migrate from JSON to a MySQL database, this will fix such annoying problems
