### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by toscan** [alexal1/Insomniac#210]
Here, two new crashes : 
[Crash-2020-12-10-12-07-24.zip](https://github.com/alexal1/Insomniac/files/5672265/Crash-2020-12-10-12-07-24.zip)
[Crash-2020-12-10-12-07-20.zip](https://github.com/alexal1/Insomniac/files/5672266/Crash-2020-12-10-12-07-20.zip)

**Comment by Fadude** [comment]
Is it still crashing on v3.6.0?
