### ISSUE TITLE
Cant unfollow private accounts

### ISSUE THREAD

**Issue by nxzoo** [alexal1/Insomniac#211]
[Crash-2020-12-11-22-27-29.zip](https://github.com/alexal1/Insomniac/files/5681699/Crash-2020-12-11-22-27-29.zip)

**Comment by evertonmdz** [comment]
Same bug here, unfollow dialog private account result in crash!

**Comment by nxzoo** [comment]
It is caused by a new pop up wheb tryibg to unfollow that is not catched in the attached zip

**Comment by evertonmdz** [comment]
If I downgrade to an older version will it work again?

**Comment by nxzoo** [comment]
Maybe

**Comment by evertonmdz** [comment]
Work again in v167.0.0.24.120 👍

**Comment by nxzoo** [comment]
Oh nice

**Comment by adchsm** [comment]
I'm still getting this issue on latest version of Insomniac + latest version of Instagram

**Comment by gionacapurso** [comment]
Same bug! Any solution?

**Comment by Fadude** [comment]
Fixed, a version will be released on next week, in the meantime you can try the beta version on
`pip install --upgrade -i https://test.pypi.org/simple/ insomniac`
 or branch `beta`

**Comment by nxzoo** [comment]
Great !
