### ISSUE TITLE
'speedtest' has no attribute 'SpeedtestException'

### ISSUE THREAD

**Issue by TriptonPt** [alexal1/Insomniac#212]
Tested on both 3.4.1 and 3.4.2 :

`Traceback (most recent call last):
  File "start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "G:\Insomniac-master\insomniac\__init__.py", line 20, in run
    insomniac_session.run()
  File "G:\Insomniac-master\insomniac\session.py", line 135, in run
    sleeper.update_random_sleep_range()
  File "G:\Insomniac-master\insomniac\sleeper.py", line 36, in update_random_sleep_range
    speed = _get_internet_speed()
  File "G:\Insomniac-master\insomniac\sleeper.py", line 67, in _get_internet_speed
    except speedtest.SpeedtestException:
AttributeError: module 'speedtest' has no attribute 'SpeedtestException'`

From what I've been reading it's an old issue and was supposed to be fixed on 3.4.1, but doesn't seem to be the case ?

**Comment by Fadude** [comment]
Please run `pip install speedtest-cli`

**Comment by twixi** [comment]
Requirement already satisfied: speedtest-cli in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (2.1.2)

**Comment by alexal1** [comment]
@twixi if you still have this error but `speedtest-cli` is installed, my version is that it's conflicting with another package. Try
```
pip uninstall speedtest
```
I once added this package to requirements.txt by mistake so it may be installed in your system.

**Comment by twixi** [comment]
i`m reinstall python and work now....
