### ISSUE TITLE
Crash Exception on first run 

### ISSUE THREAD

**Issue by TriptonPt** [alexal1/Insomniac#213]
[Crash-2020-12-13-17-14-35.zip](https://github.com/alexal1/Insomniac/files/5684526/Crash-2020-12-13-17-14-35.zip)

Crash log is attached 

Caught an exception:
-32002 Client error: <> data: Selector [childOrSibling=['child'], childOrSiblingSelector=[{'mask': 8388608, 'childOrSibling': [], 'childOrSiblingSelector': [], 'index': 4}], resourceId='com.instagram.android:id/tab_bar', className='android.widget.LinearLayout'], method: None

**Comment by Fadude** [comment]
Seems like the device is locked. Try to unlock it / set it to never be locked.
