### ISSUE TITLE
--config-file not working

### ISSUE THREAD

**Issue by metrickz** [alexal1/Insomniac#215]
Hey, I think I'm just dump but somehow I can't get the bot running with the config file.

I downloaded the interact.json edited it and put it in the same folder where the start.py file is.

then I strarted insomiac (like in the github readme):
`python3 start.py --config-file interact.json`

After the speedtest, when Insomiac is started, I get the following output:
**`Running Insomniac with two or more actions is not supported yet.`**

Is it really not supported yet or what am I doing wrong?

This is the complete cmd output:

```
C:\Users\me\Documents\GitHub\Insomniac>python3 start.py --config-file interact.json
[92m
##########################################################
#                                                        #
#   _____                                 _              #
#  |_   _|                               (_)             #
#    | |  _ __  ___  ___  _ __ ___  _ __  _  __ _  ___   #
#    | | | '_ \/ __|/ _ \| '_ ` _ \| '_ \| |/ _` |/ __|  #
#   _| |_| | | \__ \ (_) | | | | | | | | | | (_| | (__   #
#  |_____|_| |_|___/\___/|_| |_| |_|_| |_|_|\__,_|\___|  #
#                                                        #
##########################################################
[0m
[95mInsomniac v3.4.2[0m

Hi! Since of v3.1.0 all core features in this project are free to use.
You may want to get more fine grained control over the bot via these features:
    - [1mFiltering[0m - skip unwanted accounts by various parameters
    - [1mScrapping[0m - technique that makes interactions significantly safer and faster
    - [1mWorking hours[0m - the script will wait till specified hours before each session
    - [1mRemoving mass followers[0m - automate "cleaning" you account
    - [1mAnalytics tool[0m - build presentation that shows your growth
Activate by supporting our small team: [1mhttps://insomniac-bot.com/activate/[0m

Using insomniac session-manager without extra-features
Connected devices via adb: 1. That's ok.
[12/14 14:41:29] Using uiautomator v2
[12/14 14:41:32] Instagram version: 168.0.0.40.355
[12/14 14:41:32] Checking your Internet speed to adjust the script speed, please wait for a minute...
[12/14 14:41:32] (use --no-speed-check to skip this check)
[12/14 14:42:24] Download speed 55.41 Mbit/s, upload speed 24.86 Mbit/s
[12/14 14:42:24] Sleep range will be from 1.00 to 3.00 seconds
[12/14 14:42:24] Sleep time (min) before repeat: 164
Running Insomniac with two or more actions is not supported yet.

C:\Users\me\Documents\GitHub\Insomniac>
```

**Comment by Fadude** [comment]
Can you share with us your edited interact.json?

**Comment by metrickz** [comment]
[
  {
    "parameter-name": "device",
    "enabled": false,
    "value": "emulator-5554",
    "description" : "device identifier. Should be used only when multiple devices are connected at once"
  },
  {
    "parameter-name": "old",
    "enabled": false,
    "value": "True",
    "description" : "add this flag to use an old version of uiautomator. Use it only if you experience problems with the default version"
  },
  {
    "parameter-name": "no_speed_check",
    "enabled": false,
    "value": "True",
    "description" : "skip internet speed check at start"
  },
  {
    "parameter-name": "repeat",
    "enabled": true,
    "value": "160-220",
    "description" : "repeat the same session again after N minutes after completion, disabled by default. It can be a number of minutes (e.g. 180) or a range (e.g. 120-180)"
  },
  {
    "parameter-name": "likes_count",
    "enabled": true,
    "value": "2-3",
    "description" : "number of likes for each interacted user, 2 by default. It can be a number (e.g. 2) or a range (e.g. 2-4)"
  },
  {
    "parameter-name": "likes_percentage",
    "enabled": true,
    "value": "100",
    "description" : "likes given percentage of interacted users, 100 by default"
  },
  {
    "parameter-name": "stories_count",
    "enabled": false,
    "value": "1-2",
    "description" : "number of stories to watch for each user, disabled by default. It can be a number (e.g. 2) or a range (e.g. 2-4)"
  },
  {
    "parameter-name": "follow_percentage",
    "enabled": true,
    "value": "80",
    "description" : "follow given percentage of interacted users, 0 by default"
  },
  {
    "parameter-name": "interact",
    "enabled": true,
    "value": [
      "travel-top-likers",
      "@natgeo-following"
    ],
    "description" : "list of hashtags and usernames. Usernames should start with \\\"@\\\" symbol. The script will interact with hashtags\\' posts likers and with users\\' followers"
  },
  {
    "parameter-name": "reinteract_after",
    "enabled": false,
    "value": "72-96",
    "description" : "set a time (in hours) to wait before re-interact with an already interacted profile, disabled by default (won't interact again). It can be a number (e.g. 48) or a range (e.g. 50-80)"
  },
  {
    "parameter-name": "interaction_users_amount",
    "enabled": true,
    "value": "6-8",
    "description" : "add this argument to select an amount of users from the interact-list (users are randomized). It can be a number (e.g. 4) or a range (e.g. 3-8)"
  },
  {
    "parameter-name": "unfollow",
    "enabled": false,
    "value": "20-40",
    "description" : "unfollow at most given number of users. Only users followed by this script will be unfollowed. The order is from oldest to newest followings. It can be a number (e.g. 100) or a range (e.g. 100-200)"
  },
  {
    "parameter-name": "min_following",
    "enabled": false,
    "value": "150",
    "description" : "minimum amount of followings, after reaching this amount unfollow stops"
  },
  {
    "parameter-name": "max_following",
    "enabled": true,
    "value": "149",
    "description" : "maximum amount of followings, after reaching this amount follow stops. disabled by default"
  },
  {
    "parameter-name": "unfollow_non_followers",
    "enabled": true,
    "value": "20-40",
    "description" : "unfollow at most given number of users, that don\\'t follow you back. Only users followed by this script will be unfollowed. The order is from oldest to newest followings. It can be a number (e.g. 100) or a range (e.g. 100-200)"
  },
  {
    "parameter-name": "unfollow_any",
    "enabled": false,
    "value": "20-40",
    "description" : "unfollow at most given number of users. The order is from oldest to newest followings. It can be a number (e.g. 100) or a range (e.g. 100-200)"
  },
  {
    "parameter-name": "total_likes_limit",
    "enabled": true,
    "value": "50-99",
    "description" : "limit on total amount of likes during the session, 300 by default. It can be a number presenting specific limit (e.g. 300) or a range (e.g. 100-120)"
  },
  {
    "parameter-name": "total_interactions_limit",
    "enabled": true,
    "value": "50-60",
    "description" : "number of total interactions per session, disabled by default. It can be a number (e.g. 70) or a range (e.g. 60-80). Only successful interactions count"
  },
  {
    "parameter-name": "total_follow_limit",
    "enabled": true,
    "value": "30-50",
    "description" : "limit on total amount of follows during the session, disabled by default. It can be a number (e.g. 27) or a range (e.g. 20-30)"
  },
  {
    "parameter-name": "interactions_count",
    "enabled": false,
    "value": "70",
    "description" : "number of interactions per each blogger/hashtag, 70 by default. It can be a number (e.g. 70) or a range (e.g. 60-80). Only successful interactions count"
  },
  {
    "parameter-name": "follow_limit",
    "enabled": false,
    "value": "1-2",
    "description" : "limit on amount of follows during interaction with each one user's followers, disabled by default. It can be a number (e.g. 10) or a range (e.g. 6-9)"
  },
  {
    "parameter-name": "total_story_limit",
    "enabled": true,
    "value": "50-60",
    "description" : "limit on total amount of stories watches during the session, disabled by default. It can be a number (e.g. 27) or a range (e.g. 20-30)"
  },
  {
    "parameter-name": "total_get_profile_limit",
    "enabled": true,
    "value": "300-400",
    "description" : "limit on total amount of get-profile actions during the session, disabled by default. It can be a number (e.g. 600) or a range (e.g. 500-700)"
  },
  {
    "parameter-name": "session_length_in_mins_limit",
    "enabled": true,
    "value": "50-60",
    "description" : "limit the session length by time (minutes), disabled by default. It can be a number (e.g. 60) or a range (e.g. 40-70)"
  }
]

**Comment by Fadude** [comment]
You are using both `unfollow_non_followers` and `interact` actions, move `unfollow_non_followers` parameter to false and try again
