### ISSUE TITLE
interact_targets action - crash with tab_bar - share 

### ISSUE THREAD

**Issue by cecimascaras** [alexal1/Insomniac#218]
[12/16 10:53:48] Crash saved as "crashes/Crash-2020-12-16-10-53-47.zip".
[12/16 10:53:48] Please attach this file if you gonna report the crash at
[12/16 10:53:48] https://github.com/alexal1/Insomniac/issues

[12/16 10:53:48] No idea what it was. Let's try again.
[12/16 10:53:48] Close Instagram app
[12/16 10:53:48] Sleep for 1.77 seconds
[12/16 10:53:50] Open Instagram app
[12/16 10:53:50] Sleep for 2.99 seconds
[12/16 10:53:53] Press profile

Caught an exception:
-32002 Client error: <> data: Selector [childOrSibling=['child'], childOrSiblingSelector=[{'mask': 8388608, 'childOrSibling': [], 'childOrSiblingSelector': [], 'index': 4}], resourceId='com.instagram.android:id/tab_bar', className='android.widget.LinearLayout'], method: None

[Crash-2020-12-16-10-54-00.zip](https://github.com/alexal1/Insomniac/files/5703238/Crash-2020-12-16-10-54-00.zip)
[Crash-2020-12-16-10-53-47.zip](https://github.com/alexal1/Insomniac/files/5703241/Crash-2020-12-16-10-53-47.zip)
[Crash-2020-12-16-11-01-35.zip](https://github.com/alexal1/Insomniac/files/5703242/Crash-2020-12-16-11-01-35.zip)

**Comment by Fadude** [comment]
It look like in the last crash the insagram app isnt even open. Can you confirm that?

**Comment by cecimascaras** [comment]
At the end one session sucesfully, the share screen  stay open.
The next session is damage because of this.
i has send the sequente of crashs

Em qua., 16 de dez. de 2020 às 12:04, Asaf Fadida <notifications@github.com>
escreveu:

**Comment by cecimascaras** [comment]
Some names cause crash.
Can i send for you a video in telegram?

Em qua, 16 de dez de 2020 12:04, Asaf Fadida <notifications@github.com>
escreveu:

**Comment by Fadude** [comment]
Sure, you dont even need to ask :)

**Comment by cecimascaras** [comment]
Em qui., 17 de dez. de 2020 às 09:15, Asaf Fadida <notifications@github.com>
escreveu:
