### ISSUE TITLE
Running Insomniac with two or more actions is not supported yet.

### ISSUE THREAD

**Issue by rxng** [alexal1/Insomniac#219]
Hi there,

I am getting the message 

"Running Insomniac with two or more actions is not supported yet."

Using the interact.json provided on the GitHub page. Any idea what the issue is?

**Comment by Fadude** [comment]
Hi, a new version is about to be released, new configuration files will be included with it, including running two different actions one-by-one. Stay tuned :)

**Comment by Fadude** [comment]
Multi-action session is supported now using Session-Flow (v3.6.0). Please check the new config-examples directories.
