### ISSUE TITLE
Caught an exception: unconverted data remains: .154848

### ISSUE THREAD

**Issue by slauns** [alexal1/Insomniac#227]
Caught an exception:
unconverted data remains: .154848
[Crash-2020-12-23-21-30-49.zip](https://github.com/alexal1/Insomniac/files/5737225/Crash-2020-12-23-21-30-49.zip)
[Crash-2020-12-23-23-07-21.zip](https://github.com/alexal1/Insomniac/files/5737226/Crash-2020-12-23-23-07-21.zip)

**Comment by Fadude** [comment]
Fixed on v3.5.7
