### ISSUE TITLE
3.5.4 Caught an exception: unconverted data remains: .492965

### ISSUE THREAD

**Issue by slauns** [alexal1/Insomniac#228]
[Crash-2020-12-24-16-03-14.zip](https://github.com/alexal1/Insomniac/files/5739832/Crash-2020-12-24-16-03-14.zip)

**Comment by alexal1** [comment]
Thank you! I think that's enough for debugging. I'm already working on this bug

**Comment by Fadude** [comment]
Fixed on v3.5.7
