### ISSUE TITLE
Let's combine the best of both worlds

### ISSUE THREAD

**Issue by Ardy000** [alexal1/Insomniac#233]
As a user coming over from Instapy so that I could increase my daily actions without getting banned, I thought I'd share some of the actions I miss **(the actions that instapy had that insomniac doesn't)**.

[Instapy](https://github.com/timgrossmann/InstaPy) is a better bot in terms of the actions it can do.

Insomniac is a better bot in terms of not getting banned.

**Good feature to add number 1: Interact by user's likers** 
**Why is this important?** Currently Insomniac will interact with an account's followers, but the people who liked their posts are the ones **which are most likely to be active on instagram** and **the ones that like posts** so targeting them will end you up with **higher engagement ratio** 

**Implementation:**
In the same way there is `hashtag-top-likers` adding `@natgeo-likers` would be a great feature.

**Good feature to add number 2: Comment on posts** 
**Why is this important?** This will hugely increase follow back ratio of users you didn't even follow in the first place causing **authentic followers** who didn't follow you **just because** you followed them. They followed because they **genuinely** enjoy your account.

**Implementation:**
`comment-set Nice one, Great post, Love this`
`comment-percentage 20`

**Good feature to add number 3: Unfollow filter** 
Stop the unfollow from happening if user was followed less than (x) days ago
**Why is this important?** This will greatly decrease unfollow after unfollow numbers

**Implementation:**
`min-follow-time (x)*24*60*60`
`unfollow 200`

**Comment by Ardy000** [comment]
@alexal1 let me know your thoughts about this.

I am happy to help

**Comment by Fadude** [comment]
Hi @Ardy000 ,
First, thanks for your feedback!
Feature # 1 - you are totally right, and we are working on it, and the implementation will be just like you described.
Feature # 2 - Already implemented (just like to have written) and going to be released with a new version we are about to release this week.
Feature # 3 - Good point, will be added to the todo-list

**Comment by Ardy000** [comment]
Wow, 2 out of 3 already working on. I guess great minds think alike haha.

Thanks to you and your team for your work on this.

Since you've got 2/3 down, I might as well make one more recommendation from Instapy's most used features.

**Interact with commenters:**
For example:
`@natgeo-commenters`

I **just started** coding and I am learning so I _might_ be able to help implement these too.

Awesome project!
