### ISSUE TITLE
Feature request to avoid embarrassment : ) 

### ISSUE THREAD

**Issue by Ardy000** [alexal1/Insomniac#237]
**Do not interact with people I am already following**

Example:
`wildlife-top-likers`
The likers at the top of the list will **always** be my friends on Instagram as per default order. **If following user, do not interact** (like posts or comment)

Any quick fix in the .py package files?

: )

**Comment by Fadude** [comment]
Hi, there is such a filter, you just need to use filters :)

**Comment by Ardy000** [comment]
Got it thanks
