### ISSUE TITLE
Request for interact by hashtag likers

### ISSUE THREAD

**Issue by Ardy000** [alexal1/Insomniac#240]
Instead of always opening the first image from ex:`naturephotography-top-likers`, randomly pick from the top 20 images **or** don’t pick the one it already picked before (better) .

**Why?** Because after a crash, it will waste time going through the same likers list and keep saying “`already interacted`” **increasing server requests and possibly causing a ban**.

Thanks

**Comment by Fadude** [comment]
Added on v3.6.5 (selecting a random post from 1 to 20). Closing.
