### ISSUE TITLE
Unfollow not working as intended

### ISSUE THREAD

**Issue by labihi** [alexal1/Insomniac#244]
While using unfollow parameter to clean up my followings i noticed that when Insomniac decides to unfollow a user from his profile page  it can't go back to the following list, causing Insomniac to crash and reopen instagram

**Comment by Ardy000** [comment]
Same issue. Haven't narrowed it down yet. Seems to happen when trying to **unfollow a private account** where Instagram shows the popup dialogue which asks you to confirm you need to re request if you change your mind.

**Comment by adchsm** [comment]
Yep I'm also experiencing this issue, I can't unfollow anyone at the moment. 4-hour session using `--unfollow 20-30 --repeat 50-70` and 0 unfollows.

![Uploading Screenshot 2021-01-15 at 23.51.12.png…]()

**Comment by alexal1** [comment]
Thanks for feedback guys, I'm into it

**Comment by alexal1** [comment]
Can someone give me a log or a crash folder please?
[t.me/alexal1](t.me/alexal1) if it's not comfortable to post it here

**Comment by alexal1** [comment]
Is it the same problem as #253 and #254?

**Comment by Ardy000** [comment]
Most likely yes

**Comment by alexal1** [comment]
Fixed in `v3.6.6`
