### ISSUE TITLE
How does bot check for private account without actually opening the profile

### ISSUE THREAD

**Issue by Ardy000** [alexal1/Insomniac#249]
I've noticed the logs referencing fetching data to test filtered conditions (private or not, follower counts, etc.) without actually opening the profile.

Could this method be detectable by Instagram as bot behavior? I think it can. 

Do you think it's better for it to open the profile and check locally?

**Comment by Ardy000** [comment]
<img width="564" alt="Screen Shot 2021-01-17 at 1 14 12 PM" src="https://user-images.githubusercontent.com/74629332/104856216-2c9a2300-58c6-11eb-9631-03323ad185c2.png">

What is the meaning of lines 2-4 in the logs?

**Comment by Ardy000** [comment]
Could the action at line 2 be suspicious like bot activity by Instagram?

**Comment by alexal1** [comment]
@Ardy000
> Could the action at line 2 be suspicious like bot activity by Instagram?

This action is similar to opening someone's profile in browser incognito tab. You'll have to do profile-view action anyway, so this probably just gives you some number of "free" profile-views. But if you think it can somehow make Instagram think you're using a bot, then we can add a flag to disable this feature.

**Comment by Ardy000** [comment]
> But if you think it can somehow make Instagram think you're using a bot

I think they can detect in two ways: 
1. It's not possible for human to open in incognito browser when using the app. Plus your device address is still there so I don't think it'll be free profile-views.

**2. I think it is detectable since if it doesn't download images (profile pic, first 9 posts, highlight previews) from Instagram servers then it's suspicious like a bot with no GUI **

> But if you think it can somehow make Instagram think you're using a bot, then we can add a flag to disable this feature

I don't think it has any benefit and is suspicious activity so please do add a flag to disable that feature thanks so much for taking feedback from users and implementing it in a timely manner too.

**Comment by Ardy000** [comment]
@alexal1 

Is there any quick fix in the .py source files I can do right now?

**Comment by alexal1** [comment]
@Ardy000 there's no quick fix, but created this beta for you: https://test.pypi.org/project/insomniac/3.6.6.2/
No fetching by default, `--fetch-profiles-from-net` to bring it back. Enjoy

**Comment by Ardy000** [comment]
Wow that’s amazing 

Thank you
