### ISSUE TITLE
FEATURE - device.screen.on()  / device.screen.off() 

### ISSUE THREAD

**Issue by gvmturl** [alexal1/Insomniac#25]
As @GabrieleAnsaldo commented on Telegram Group "This comes usefull if for instance you keep your phone connected whole time, consider on and off"

Open as issue to discuss and follow implementation.

**Comment by alexal1** [comment]
What if phone is blocked by pin/password/gesture/etc? I'm certain there is no way to unblock the phone via adb.

**Comment by GabrieleAnsaldo** [comment]
It all depends if you’re using your everyday android phone or not. If not then you can make sure you don’t set a pin. Otherwise have a look at this:

https://stackoverflow.com/questions/29072501/how-to-unlock-android-phone-through-adb
