### ISSUE TITLE
Crash when unfollow confirmation dialog appears (unfollowing private profiles)

### ISSUE THREAD

**Issue by gionacap** [alexal1/Insomniac#253]
Hello, 

The bot is crashing when attempts to unfollow a private profile and the pop-up "If you change your mind, you'll have to request to follow again" appears. 
I tried this multiple times and is always crashing when unfollowing a private profile. 
[Crash-2021-01-18-10-59-57.zip](https://github.com/alexal1/Insomniac/files/5829845/Crash-2021-01-18-10-59-57.zip)

**Comment by simonmannsfeld** [comment]
I've an easy fix for this. Just remove line `822` in `.../insomniac/actions_impl.py`.

This line should include `className='android.widget.TextView',`.

**Comment by gionacap** [comment]
Thank you! I fixed it by downgrading Insta but still I wanted to let you guys know 👍

**Comment by alexal1** [comment]
Fixed in `v3.6.6`
