### ISSUE TITLE
Crash when unfollow private account - Confirm dialog

### ISSUE THREAD

**Issue by bigshadowesp** [alexal1/Insomniac#254]
Hello,
When the bot are unfollowing any user who has a private account, Instagram shows a confirm dialog.
In that moment the program crash.
I attach the crash report.

Ty and wait your help.
[Crash-2021-01-18-18-22-05.zip](https://github.com/alexal1/Insomniac/files/5831673/Crash-2021-01-18-18-22-05.zip)

**Comment by simonmannsfeld** [comment]
I've an easy fix for this. Just remove line `822` in `.../insomniac/actions_impl.py`.

This line should include `className='android.widget.TextView',`.

**Comment by alexal1** [comment]
Fixed in `v3.6.6`
