### ISSUE TITLE
Crash caused by share interaction

### ISSUE THREAD

**Issue by mv-debug** [alexal1/Insomniac#263]
Hi, 

I recognize multiple crashes with my bot (every second  attempt). But I am not understanding why this is happen. It seems that the bot pressed the share button. Do you have got an idea?

[Crash-2021-02-08-10-55-40.zip](https://github.com/alexal1/Insomniac/files/5942964/Crash-2021-02-08-10-55-40.zip)
[Crash-2021-02-08-10-55-52.zip](https://github.com/alexal1/Insomniac/files/5942965/Crash-2021-02-08-10-55-52.zip)

Thank you in advanced.

**Comment by alexal1** [comment]
Already investigating this problem, thanks for crashes info

**Comment by alexal1** [comment]
Found a solution, will be fixed in `v3.6.7` (release tomorrow)

**Comment by mv-debug** [comment]
@alexal1 Great. This is agile development :)
