### ISSUE TITLE
If Insomniac sees "Follow Back" instead of follow, will it skip?

### ISSUE THREAD

**Issue by Ardy000** [alexal1/Insomniac#265]
If it doesn't, then can we add a filter similar to 

skip already following profiles?
and add one like
skip already followers profiles

Or does it do this by default already?

Any quick fix in the source .py files I can do myself? For example set "follow back" text to trigger same response as "following" so that it will skip them when using the already present filter

Thanks

**Comment by shifenis** [comment]
I don't understand if you want a thing like my issue (#268). 
If so, I'm currently working on it.

**Comment by alexal1** [comment]
Added `"skip_already_following_profiles" : true` filter
