### ISSUE TITLE
Prevent interact with already followed users

### ISSUE THREAD

**Issue by shifenis** [alexal1/Insomniac#268]
Like the title, it would be awesome if `Insomniac` could avoid interacting with the already followed users, even the users followed 
by users.
I didn't find any references to this in the doc, so I'll describe a scenario. 

## Scenario: 
The user trying to interact with User x, this one follows mutual users, so these will be on top of the list and the interact script will interact.

## Desired
Add the possibility to add some flag (like `-skip-mutual`) in `interact`, for examples:

```--interact @natgeo-following-skip-mutual```.

I'll try to implement it myself, and send a PR, but I think this is could be helpful for tracking or other devs.

**Comment by Fadude** [comment]
Sounds great! PRs are most welcome!

**Comment by alexal1** [comment]
Looks like we already have this feature: use [filters](https://insomniac-bot.com/docs/#/?id=filters): `"skip_already_following_profiles": true`
