### ISSUE TITLE
FEATURE - Stop if is blocked

### ISSUE THREAD

**Issue by gvmturl** [alexal1/Insomniac#27]
Open as issue to discuss and follow implementation.

@GabrieleAnsaldo

**Comment by alexal1** [comment]
If anyone attach here a `uiautomatorviewer` screenshot like @jonap339 did in https://github.com/alexal1/Insomniac/issues/7#issuecomment-643024501, it will be very helpful. I need a screenshot of a dialog window that notifies that you got blocked.

**Comment by jonap339** [comment]
As soon as I get rid of my job, I attach it! :)

**Comment by gvmturl** [comment]
Something that i could check here... i got a message that action is blocked on my iphone with an account, so i logged it on android and got no action blocked.... you guys know how this block works?

**Comment by jonap339** [comment]
Sure, what happened was that that instagram blocked your device, not your account. Therefore, if you enter from another device, you can continue working normally, please note that Instagram will be watching you closely. There are two types of blocks. The temporary lock in which the device first locks but not your account. The other block is when it indicates in the window until which date it is blocked, that is. As much as you enter from any device, you will see the same block.

**Comment by jonap339** [comment]
> If anyone attaches here a `uiautomatorviewer` screenshot like @jonap339 did in [#7 (comment)](https://github.com/alexal1/Insomniac/issues/7#issuecomment-643024501), it will be very helpful. I need a screenshot of a dialog window that notifies that you got blocked.

@alexal1 Attached Lock Screen Capture ;) 

[Block.zip](https://github.com/alexal1/Insomniac/files/4794976/Block.zip)
