### ISSUE TITLE
Filters ignoring

### ISSUE THREAD

**Issue by canberkkurtulmus** [alexal1/Insomniac#273]
Hi everyone, I have a problem with filters, ı choosed max and min values for the following and followings but the bot some times just ignores that parameters, does anyone had the same problem or I am doing something wrong?
[interact.txt](https://github.com/alexal1/Insomniac/files/6031683/interact.txt)
[insomniac_log-2021-02-23-23-15-56.log](https://github.com/alexal1/Insomniac/files/6031684/insomniac_log-2021-02-23-23-15-56.log)

**Comment by alexal1** [comment]
You did everything right, it's just because filters are an extra feature. You have to get your activation code: [INSTALL_FAILED_VERIFICATION_FAILURE
