### ISSUE TITLE
Traceback (most recent call last):   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/insomniac/device_facade.py", line 545, in get_bounds

### ISSUE THREAD

**Issue by mdlaizure** [alexal1/Insomniac#276]
The latest release didn't fix this crash.
[Crash-2021-02-24-05-48-05.zip](https://github.com/alexal1/Insomniac/files/6035680/Crash-2021-02-24-05-48-05.zip)
[Crash-2021-02-24-05-45-59.zip](https://github.com/alexal1/Insomniac/files/6035681/Crash-2021-02-24-05-45-59.zip)
[Crash-2021-02-24-05-44-41.zip](https://github.com/alexal1/Insomniac/files/6035682/Crash-2021-02-24-05-44-41.zip)
[Crash-2021-02-24-05-43-26.zip](https://github.com/alexal1/Insomniac/files/6035683/Crash-2021-02-24-05-43-26.zip)
[Crash-2021-02-24-05-40-55.zip](https://github.com/alexal1/Insomniac/files/6035684/Crash-2021-02-24-05-40-55.zip)
[Crash-2021-02-24-05-39-48.zip](https://github.com/alexal1/Insomniac/files/6035685/Crash-2021-02-24-05-39-48.zip)
[Crash-2021-02-24-05-38-45.zip](https://github.com/alexal1/Insomniac/files/6035686/Crash-2021-02-24-05-38-45.zip)
[Crash-2021-02-24-05-37-35.zip](https://github.com/alexal1/Insomniac/files/6035687/Crash-2021-02-24-05-37-35.zip)
[insomniac_log-2021-02-23-16-48-52.log](https://github.com/alexal1/Insomniac/files/6035691/insomniac_log-2021-02-23-16-48-52.log)

**Comment by alexal1** [comment]
Fixed in `v3.7.0`
