### ISSUE TITLE
Error During Open Blogger's followers -SOLVED

### ISSUE THREAD

**Issue by vanders22** [alexal1/Insomniac#28]
EDIT: Solved by reinstalling the app

 i'm stuck on this fase, all work ok, but during open followers this error appears:

File "/.../python3.8/site-packages/uiautomator/__init__.py", line 133, in __call__      
    raise JsonRPCError(                                                                                    
uiautomator.JsonRPCError: JsonRPC Error code: -32002, Message: android.support.test.uiautomator.UiObjectNotFoundException: UiSelector[CLASS=android.widget.LinearLayout, RESOURCE_ID=com.instagram.android:id/row_profile_header_followers_container]   

PS: the program seems AWESOME

**Comment by alexal1** [comment]
> the program seems AWESOME

Thanks!

**Comment by sanderpuh** [comment]
How did you solve the issue? I have the same issue at the moment.
