### ISSUE TITLE
Crash while trying to like video post

### ISSUE THREAD

**Issue by mdlaizure** [alexal1/Insomniac#283]
[Crash-2021-03-07-14-57-30.zip](https://github.com/alexal1/Insomniac/files/6097921/Crash-2021-03-07-14-57-30.zip)
[Crash-2021-03-07-15-10-28.zip](https://github.com/alexal1/Insomniac/files/6097922/Crash-2021-03-07-15-10-28.zip)

**Comment by alexal1** [comment]
Fixed in `v3.7.0`
