### ISSUE TITLE
failed to install ADB Keyboard v3.7.0

### ISSUE THREAD

**Issue by linice930** [alexal1/Insomniac#289]
[03/19 23:45:22] Installing ADB Keyboard to enable typewriting...
adb: failed to install C:\Users\sgobi\AppData\Local\Programs\Python\Python39\lib\site-packages\insomniac\apk\ADBKeyboard.apk: Failure [INSTALL_FAILED_VERIFICATION_FAILURE]
[03/19 23:45:32] Cannot setup ADB Keyboard. Don't worry! Fallback to text copy-pasting will be used.

**Comment by marco1m** [comment]
I have the same problem!

**Comment by alexal1** [comment]
@linice930 @marco1m hey guys! I cannot reproduce this issue, but I think I understand the reason. Please try to go to developer settings and disable verify apps via USB.

**Comment by linice930** [comment]
how to go to developer settings ?
