### ISSUE TITLE
No likes, let's scroll down....

### ISSUE THREAD

**Issue by Contenterofficial** [alexal1/Insomniac#290]
No likes, let's scroll down issue, keeps scrolling and hitting a wall in the likers section. It does not crash by itself, but I have to go back few steps and then it crashes!
[insomniac_log-2021-03-19-15-38-11.log](https://github.com/alexal1/Insomniac/files/6172586/insomniac_log-2021-03-19-15-38-11.log)
[Crash-2021-03-19-17-01-31.zip](https://github.com/alexal1/Insomniac/files/6172590/Crash-2021-03-19-17-01-31.zip)

**Comment by alexal1** [comment]
According to the logs it's `v3.6.10`. It was fixed in `v3.7.0`
