### ISSUE TITLE
v3.7.0 | bot doesn't write username in search bar resulting in crash

### ISSUE THREAD

**Issue by nxzoo** [alexal1/Insomniac#295]
https://user-images.githubusercontent.com/56136151/112100252-1ef26980-8ba5-11eb-81ae-2659016ff828.mp4

[Crash-2021-03-23-06-51-37.zip](https://github.com/alexal1/Insomniac/files/6187202/Crash-2021-03-23-06-51-37.zip)

**Comment by nxzoo** [comment]
with --no-typing the bot succeeded

**Comment by marco1m** [comment]
how did you solve this?
