### ISSUE TITLE
Error with private account

### ISSUE THREAD

**Issue by Foncekar** [alexal1/Insomniac#3]
If one follower of the target account is private then the process stop with error 
"Probably need to scroll"
I think we need to find a way to avoid private account.

**Comment by alexal1** [comment]
Are you sure that it is a stop, not a long pause (like 1-2 minutes)?
I just tested this case and everything's fine, here is my log:

```
@alextikhov: interact
Sleep for 3 seconds
Open and like photo #1 (2 row, 2 column)
Probably need to scroll.
Less than 6 photos / account is private. Skip user.
Back to followers list
```

**Comment by Foncekar** [comment]
yes my bad, the sleep time in my phone was too short.

**Comment by alexal1** [comment]
@Foncekar a little tip: there is a switch in developer settings in Android, that makes the device never sleep if it is being charged.
