### ISSUE TITLE
Liking issue

### ISSUE THREAD

**Issue by joezawinul** [alexal1/Insomniac#30]
I experienced an issue, my script crash after 'double click' in the comments section instead of the actual photo/video.

My guess is that depending on the device you use, the coordinates of the action taken by the script (e.g. double click) are different. For example, I have a Huawei P30 Pro with a very big screen, the not square sized photos/videos shown a way higher than the center of my screen. Then, during the 'double click' action for liking it seems to click on the comments/description (e.g. on hashtags) when the photo/video is not square sized.

A solution may be to get dynamic coordinates from the photos/videos (or maybe to know what size they are) before 'double clicking' to adjust where the 'double click' happens.

**Comment by alexal1** [comment]
Since of `v2.0.0` double click is made exactly at the center of visible part of the photo/video.
