### ISSUE TITLE
interact with posts of hashtags

### ISSUE THREAD

**Issue by skiwlkr** [alexal1/Insomniac#301]
I just switched from instapy to Insomniac because I read some good reviews of it.
I'm slowly tapping into all the different commands but so far I can't get Insomniac to like posts of a specific hashtag.
Only recent-likers and top-likers of a hashtag or followers/following of a user.
I wonder if this is even possible? 
The reason why I'm asking is when you want to target the people who create - let's say Art - its quite a difference from people who just like arts or the people who following arts. It's quite hard to get specific type of audience that way.
Maybe I'm just blind and can't see the feature right now.

**Comment by jfilipefreitas** [comment]
Hi, also with the same issue, did you find a solution for this?

**Comment by NikiZ97** [comment]
Is there a way to like also some posts from users from recents? Say you tap "Recents" tab, then you choose a user from list, go to their profile and then like some posts of this user.
