### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Gabnator2002** [alexal1/Insomniac#302]
> [
[Crash-2021-04-01-18-33-57.zip](https://github.com/alexal1/Insomniac/files/6246314/Crash-2021-04-01-18-33-57.zip)
[Crash-2021-04-01-18-33-38.zip](https://github.com/alexal1/Insomniac/files/6246316/Crash-2021-04-01-18-33-38.zip)

](url)

**Comment by mdlaizure** [comment]
Fixed in 3.7.2 release
