### ISSUE TITLE
First run after 3.7.1 upgrade

### ISSUE THREAD

**Issue by mdlaizure** [alexal1/Insomniac#303]
It happened the same on the first 2 accounts I tried...
Caught an exception:
NOT NULL constraint failed: instagram_profiles_info.followers
[04/02 07:53:15] Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/peewee.py", line 3144, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: instagram_profiles_info.followers

[crash and log.zip](https://github.com/alexal1/Insomniac/files/6249400/crash.and.log.zip)

**Comment by Fadude** [comment]
Should fixed under 3.7.2. Can you please confirm?
