### ISSUE TITLE
Common crash so far in 3.7.1

### ISSUE THREAD

**Issue by mdlaizure** [alexal1/Insomniac#304]
[04/02 09:21:59] Didn't find tab HOME in the tab bar... Maybe English language is not set!?

[crashandlog.zip](https://github.com/alexal1/Insomniac/files/6249914/crashandlog.zip)

**Comment by mdlaizure** [comment]
happening often...

**Comment by linice930** [comment]
yes, same here...

**Comment by Fadude** [comment]
Please let us know is the issue still happen on 3.7.2

**Comment by linice930** [comment]
i think yes, still have same issue on 3.7.2

**Comment by mdlaizure** [comment]
3.7.2 fixed it for me. Many runs now across serval accounts.
