### ISSUE TITLE
Unfollow not working [no data about followed user and interactions saved to the database]

### ISSUE THREAD

**Issue by wojciechsmol** [alexal1/Insomniac#319]
Me and many guys from discord have the same issues which is it seems that data about followed and interacted accounts is not saved or not read properly, which causes unfollow action to fail and it does not unfollow any people.

**It seems like the bot is just not filling the "follow_status" In the Insomniac.db**

So basically after bot followed and interacted with many users it still does not unfollow any people despite my command being:

![Screen Shot 2021-04-14 at 19 58 50](https://user-images.githubusercontent.com/15012920/114757189-d66d3c80-9d5b-11eb-957c-fc57d11aff34.png)

This is the end of the logs during unfollow action:

![image](https://user-images.githubusercontent.com/15012920/114757116-bfc6e580-9d5b-11eb-8a71-4003e75db1a6.png)

Also this is is what one of the guys wrote on the discord:

![Screen Shot 2021-04-14 at 19 57 54](https://user-images.githubusercontent.com/15012920/114757085-b473ba00-9d5b-11eb-83fb-df6939fff02d.png)

There is also a problem with saving interactions to the database. That's what one of the users said:

![Screen Shot 2021-04-14 at 20 00 14](https://user-images.githubusercontent.com/15012920/114757348-07e60800-9d5c-11eb-853b-e6d6090c911b.png)

**Comment by JJChelsea** [comment]
I have the same problem as wojciechsmol. Either the bot has not saved a record of the accounts it has followed or it is not retrieving the database properly when iterating over the list of currently following profiles.  Every account it has followed that it finds in the list of currently following profiles, it incorrectly says "Skip @[ACCOUNTNAME]. Following status: UNFOLLOWED (probably not followed by the bot...)". But the following status is not unfollowed.  I am at a loss as to how to fix this.

**Comment by alexal1** [comment]
Fixed in `v3.7.11`.
Older versions weren't writing to the database that profile was followed by the bot itself. Sorry for this issue. You can run unfollowing with `--unfollow-followed-by-anyone` and use whitelist.
