### ISSUE TITLE
Script runs but nothing happens

### ISSUE THREAD

**Issue by jduhautois** [alexal1/Insomniac#32]
I'm really excited to make this project work. When running the script everything looks smooth. However, nothing happens. Any pointers as to where to start for troubleshooting? Thank you!

_[06/26 14:33:55] Connected devices via adb: 1. That's ok.
usage: insomniac.py [--interact usta [playyourcourt ...]] [--likes-count 2] [--total-likes-limit 1000] [--interactions-count 100] [--repeat 180] [--follow-percentage 50] [--unfollow 100] [--unfollow-non-followers 100]

Instagram bot for automated Instagram interaction using Android device via ADB

optional arguments:
  --interact usta [playyourcourt ...]
                        list of usernames with whose followers you want to interact
  --likes-count 2       number of likes for each interacted user, 2 by default
  --total-likes-limit 1000
                        limit on total amount of likes during the session, 1000 by default
  --interactions-count 100
                        number of interactions per each blogger, 100 by default
  --repeat 180          repeat the same session again after N minutes after completion, disabled by default
  --follow-percentage 50
                        follow given percentage of interacted users, 0 by default
  --unfollow 100        unfollow at most given number of users. Only users followed by this script will be unfollowed. The order is from oldest to newest followings
  --unfollow-non-followers 100
                        unfollow at most given number of users, that don't follow you back. Only users followed by this script will be unfollowed. The order is from oldest to newest followings_

**Comment by Foncekar** [comment]
Could you tell us which command you use to launch the script ?

**Comment by jduhautois** [comment]
I run the Python file in the Terminal from Visual Studio Code.

**Comment by private80** [comment]
I have the same problem. The script runs but nothing happens.

**Comment by Foncekar** [comment]
ok, so if you only use this command 
`python3 insomniac.py`
It's normal if the script do nothing, you have to use arguments like that : 
`python3 insomniac.py --likes-count 3 --total-likes-limit 128 --interactions-count 54 --repeat 180 --follow-percentage 50 --unfollow-non-followers 100 --interact accounttarget1 accounttarget2 `

**Comment by private80** [comment]
Thank you so much for clearing that up. Do all arguments need to be specified? It is currently saying running Insomniac with two or more actions is not supported yet even though only one phone is connected.

**Comment by private80** [comment]
Oh I think I got it figured out, it can't unfollow and follow at the same time it seems like.

**Comment by Foncekar** [comment]
He only unsubscribes from accounts where he followed previously.

**Comment by jduhautois** [comment]
Replying here since it is related. I can't seem to enter the right arguments to make unfollowing work. I keep receiving the error _"Running Insomniac with two or more actions is not supported yet."_

I have the following arguments and run the following command 

**Command:**
python insomniac.py --unfollow-non-followers 100

**Arguments:**
   parser.add_argument('--interact',
                        nargs='+',
                        help='list of usernames with whose followers you want to interact',
                        metavar=(''),
                        default=[''])
    parser.add_argument('--likes-count',
                        help='number of likes for each interacted user, 2 by default',
                        metavar='',
                        default=0)
    parser.add_argument('--total-likes-limit',
                        help='limit on total amount of likes during the session, 1000 by default',
                        metavar='',
                        default=0)
    parser.add_argument('--interactions-count',
                        help='number of interactions per each blogger, 100 by default',
                        metavar='',
                        default=0)
    parser.add_argument('--repeat',
                        help='repeat the same session again after N minutes after completion, disabled by default',
                        metavar='')
    parser.add_argument('--follow-percentage',
                        help='follow given percentage of interacted users, 0 by default',
                        metavar='',
                        default=0)
    parser.add_argument('--unfollow',
                        help='unfollow at most given number of users. Only users followed by this script will '
                             'be unfollowed. The order is from oldest to newest followings',
                        metavar='',
                        default='0')
    parser.add_argument('--unfollow-non-followers',
                        help='unfollow at most given number of users, that don\'t follow you back. Only users followed '
                             'by this script will be unfollowed. The order is from oldest to newest followings',
                        metavar='100',
                        default='100')
