### ISSUE TITLE
Script is liking but not following

### ISSUE THREAD

**Issue by rxng** [alexal1/Insomniac#320]
It has been about 10 users interacted with and Insomniac is still not following any of them

This is my current follow percentage

```
"parameter-name": "follow_percentage",
    "enabled": true,
    "value": "80",
    "description" : "follow given percentage of interacted users, 0 by default"
```

`Session progress: 15 likes, 0 followed, 0 stories watched, 0 comments, 0 successful interactions for #foodie, 9 successful interactions for the entire session`

**Comment by alexal1** [comment]
That's strange, attach a full log please, maybe there are some errors

**Comment by rxng** [comment]
[insomniac_log-2021-04-16-17-46-49.log](https://github.com/alexal1/Insomniac/files/6332430/insomniac_log-2021-04-16-17-46-49.log)

@alexal1

**Comment by rxng** [comment]
Will this issue be fixed? Seems pretty critical feature

**Comment by rxng** [comment]
Hi @alexal1 just updated to the latest version of insomniac, however, this bug is still there and the bot is still only liking but not following

**Comment by alexal1** [comment]
@rxng even if you set `"value": "100"`?

**Comment by rxng** [comment]
@alexal1 fixed with uninstall and then an upgrade of insomniac
