### ISSUE TITLE
Cannot find tab: Accounts.

### ISSUE THREAD

**Issue by RaynoldVanHeyningen** [alexal1/Insomniac#326]
Been getting this issue since the start of this week, which makes me unable to use the app.

Would love to get some help, how to fix this issue :)!

[Crash-2021-04-26-16-47-04.zip](https://github.com/alexal1/Insomniac/files/6389567/Crash-2021-04-26-16-47-04.zip)

**Comment by RaynoldVanHeyningen** [comment]
Seems like it's working! Great workaround, thanks alot

**Comment by alexal1** [comment]
Fixed in `v3.7.11`
