### ISSUE TITLE
Didn't find tab HOME in the tab bar... Maybe English language is not set!?

### ISSUE THREAD

**Issue by AidenH2970** [alexal1/Insomniac#330]
I don't know how to fix this can someone please help?

[Crash-2021-05-05-02-19-44.zip](https://github.com/alexal1/Insomniac/files/6426115/Crash-2021-05-05-02-19-44.zip)

<img width="571" alt="Screen Shot 2021-05-05 at 2 30 05 AM" src="https://user-images.githubusercontent.com/83699362/117121699-d0122500-ad49-11eb-94d3-06cca5849efb.png">

**Comment by alexal1** [comment]
Fixed in `v3.7.11`

**Comment by 710colombiano** [comment]
im getting thism issue in 3.7.12  can anyone help me?

**Comment by 710colombiano** [comment]
UPDATE: i saw there was a new version of INSOMNIAC (3.7.12) i downloaded that restarted my PC and walla im back automating. Thank you for fixing the issue!

**Comment by alexal1** [comment]
@710colombiano you're welcome :)
