### ISSUE TITLE
Couldn't switch user to scraper, abort!

### ISSUE THREAD

**Issue by Paris704** [alexal1/Insomniac#336]
My android emulator manages to log into my scraper account but for some reason insomniac says it can't switch users and crashes. (even though it is logged in and the page shows on my emulator screen).

it prints this message "Couldn't switch user to scraper, abort!"

I recently had to create a new scrapping account because the other one has a soft ban on it. The bot seem to only accept to work with my original scraper.

**Comment by zubus** [comment]
Hi, try GramAddict ([https://github.com/GramAddict/bot/](https://github.com/GramAddict/bot/)) it is an open source (and 100% free!) Fork of Insomniac, it has this and many bugs already fixed and a great community ;)

**Comment by marcosalvadori** [comment]
Same problem.

**Comment by alexal1** [comment]
Fixed in `v3.7.14`
