### ISSUE TITLE
New database system ignored accounts without interacion. 

### ISSUE THREAD

**Issue by cecimascaras** [alexal1/Insomniac#337]
i need know how correct this problem via SQL commands. 

Can i delete of new database the user and putting in the targets.txt? What tables or registries? 

They are on the like_actions table as I see

**Comment by zubus** [comment]
Hi, try GramAddict ([https://github.com/GramAddict/bot/](https://github.com/GramAddict/bot/)) it is an open source (and 100% free!) Fork of Insomniac, it has this and many bugs already fixed and a great community ;)

**Comment by cecimascaras** [comment]
EXPORTEI TODOS OS REGISTROS PARA TARGETS.TXT
