### ISSUE TITLE
Action restricted on every like even after cooldown

### ISSUE THREAD

**Issue by skiwlkr** [alexal1/Insomniac#339]
Since last week I get the Message
"Try again later we restrict certain activity..."

First I thought - okay another soft ban, lets wait unitl it cooled down.
Haven't used Insomniac now for several days, but sitll on the first like I get the message that the interaction is restricted.

I can do all interactions on the account manually with my phone from the same network.
Can Instagram detect a Memu Instance? I thought that's not possible. Correct me if I'm wrong :)

Appreciate any help! Thanks!

**Comment by alexal1** [comment]
1. Did you try to reinstall Instagram app on your Memu?
2. Yes, it's possible to detect emulator, but nobody knows if Instagram does it or not.

**Comment by skiwlkr** [comment]
Thanks for the help.
Reinstalling the app solved the problem!
