### ISSUE TITLE
working hours setting does not work

### ISSUE THREAD

**Issue by rxng** [alexal1/Insomniac#340]
Interact.json has this setting

```
{
    "parameter-name": "working_hours",
    "enabled": true,
    "value": "4-6",
    "description" : "set working hours to the script, disabled by default. It can be a number presenting specific hour (e.g. 13) or a range (e.g. 9-21)"
  },
```

However, total duration is 8 hours

Total duration: 8:02:54.464267

**Comment by zubus** [comment]
Hi, try GramAddict (https://github.com/GramAddict/bot/) it is an open source (and 100% free!) Fork of Insomniac, it has this and many bugs already fixed and a great community ;)

**Comment by alexal1** [comment]
@rxng `working_hours` means time when script can be launched. If you want to limit session length, use
```
{
    "parameter-name": "session_length_in_mins_limit",
    "enabled": true,
    "value": "40-80",
    "description" : "limit the session length by time (minutes), disabled by default. It can be a number (e.g. 60) or a range (e.g. 40-70)"
},
```
