### ISSUE TITLE
uiautomator2.exceptions.UiObjectNotFoundError: -32001 Jsonrpc error

### ISSUE THREAD

**Issue by minsuh04** [alexal1/Insomniac#344]
can't scroll down ... 

[Crash-2021-06-14-23-08-46.zip](https://github.com/alexal1/Insomniac/files/6648924/Crash-2021-06-14-23-08-46.zip)

**Comment by alexal1** [comment]
Will be fixed in `v3.7.15`!

**Comment by babytabie** [comment]
It wasnt fixed
