### ISSUE TITLE
Is there a way to interact with your feed? 

### ISSUE THREAD

**Issue by potatoxbe** [alexal1/Insomniac#346]
I might be missing something, but can't seem to find the settings. Is there anyway I can interact with posts in my feed? Of people whom I've followed?

**Comment by simonmannsfeld** [comment]
@potatoxbe why do you want to do this? I cannot find the point. Please explain it to me. ☺️

**Comment by potatoxbe** [comment]
I'd like to interact with my followers/following too ☺️. To keep them engaged with my account for a longer term, not just a few times liking and follow up front. I've been doing that with the other Firefox using bot. Would be great if I can use yours too, since it's been a lot more stable for me so far.

**Comment by alexal1** [comment]
Hi @potatoxbe!
There are two ways right now:
1. Get an [activation code](https://insomniac-bot.com/activate/) and use **warmup feature** (`--warmup-time-before-session 3-8`). Then bot will scroll your feed and like random posts, then open search and scroll Explore feed and like random posts from there.
2. Use `--interact <your username>` to interact with your own followers.

**Comment by alexal1** [comment]
Please close the issue if it fully answers your question, or create an issue with feature request if that's not enough. Thank you.
