### ISSUE TITLE
DEAD?

### ISSUE THREAD

**Issue by Diogovski** [alexal1/Insomniac#348]
Is this project dead? I don't see support at all and only people complaning ( i know it's because of instagram UI update). I wanted to use this and even support it threw patreon, but i need someone to tell me that there is an actual team

**Comment by zubus** [comment]
Hi, look at [GramAddict](https://github.com/GramAddict/bot/) a free Insomniac fork without issues and a great team!

**Comment by alexal1** [comment]
(ads is not welcome in the community)

**Comment by alexal1** [comment]
@Diogovski **no, project is not dead.**
I'm right now working on a new release where all new issues will be fixed.

**Comment by mastrolube** [comment]
> (ads is not welcome in the community)

Interesting, I saw the reply you deleted. Advertising by suggesting a free project. Are you kidding me? Lol


By the way is on instapy also not welcome? So why I saw your spam for every release?

I have no words.
Cheers 🥂

**Comment by alexal1** [comment]
(offtopic, we don't discuss promotion of projects here)
