### ISSUE TITLE
Filter business accounts

### ISSUE THREAD

**Issue by michaelmagro** [alexal1/Insomniac#35]
Is there a possibility to validate whether an account is a business account before interacting with it?

**Comment by alexal1** [comment]
Yeah, that can be done, but what for? Anyone can mark their account as "business" even if they've nothing to do with business. There are a lot of people who do this just to have enhanced statistics.

So, technically this can be done, but I don't see the reason.

**Comment by michaelmagro** [comment]
It is because I have an instagram account that promotes b2b services in my city, I would like to interact with business profiles at first and test the effectiveness of this for my business niche.


What would be an easier way? I think I could implement it myself but I need a direction..

**Comment by alexal1** [comment]
Feature implemented.
