### ISSUE TITLE
Cannot get module actions_impl from v3.7.13: 403 (Forbidden)

### ISSUE THREAD

**Issue by edukessen** [alexal1/Insomniac#351]
Tried updating via the command `python3 -m pip install insomniac --upgrade` says already satisfied, but still 3.7.13 when I try to run it again. I can't make it past this step. First time installing. Here is the full error.

[06/21 07:58:01] Cannot get module actions_impl from v3.7.13: 403 (Forbidden)
Traceback (most recent call last):
  File "C:\Users\eddiejag\OneDrive\Desktop\PROGRAMS\Insomniac-master\start.py", line 4, in <module>
    insomniac.run(activation_code)
  File "C:\Users\eddiejag\OneDrive\Desktop\PROGRAMS\Insomniac-master\insomniac\__init__.py", line 23, in run
    from insomniac.session import InsomniacSession
  File "C:\Users\eddiejag\OneDrive\Desktop\PROGRAMS\Insomniac-master\insomniac\session.py", line 4, in <module>
    from insomniac.action_runners.actions_runners_manager import ActionRunnersManager
  File "C:\Users\eddiejag\OneDrive\Desktop\PROGRAMS\Insomniac-master\insomniac\action_runners\__init__.py", line 2, in <module>
    from insomniac.action_runners.interact import InteractBySourceActionRunner, InteractByTargetsActionRunner
  File "C:\Users\eddiejag\OneDrive\Desktop\PROGRAMS\Insomniac-master\insomniac\action_runners\interact\__init__.py", line 3, in <module>
    from insomniac.safely_runner import run_safely
  File "C:\Users\eddiejag\OneDrive\Desktop\PROGRAMS\Insomniac-master\insomniac\safely_runner.py", line 5, in <module>
    from insomniac.extra_features.actions_impl import airplane_mode_on_off
  File "C:\Users\eddiejag\OneDrive\Desktop\PROGRAMS\Insomniac-master\insomniac\extra_features\actions_impl.py", line 3, in <module>
    exec(activation_controller.get_extra_feature('actions_impl'))
TypeError: exec() arg 1 must be a string, bytes or code object

**Comment by alexal1** [comment]
Fixed in `v3.7.14`

**Comment by edukessen** [comment]
When I try to upgrade via the pip command, it gives me this 

WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python39\lib\site-packages)
Requirement already satisfied: insomniac in c:\python39\lib\site-packages (3.7.14)
Requirement already satisfied: colorama in c:\python39\lib\site-packages (from insomniac) (0.4.4)
Requirement already satisfied: sourcedefender in c:\python39\lib\site-packages (from insomniac) (7.1.14)
Requirement already satisfied: uiautomator in c:\python39\lib\site-packages (from insomniac) (1.0.2)
Requirement already satisfied: peewee in c:\python39\lib\site-packages (from insomniac) (3.14.4)
Requirement already satisfied: uiautomator2 in c:\python39\lib\site-packages (from insomniac) (2.16.0)
Requirement already satisfied: croniter in c:\python39\lib\site-packages (from insomniac) (1.0.13)
Requirement already satisfied: python-dateutil in c:\users\eddiejag\appdata\roaming\python\python39\site-packages (from croniter->insomniac) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\python39\lib\site-packages (from python-dateutil->croniter->insomniac) (1.16.0)
Requirement already satisfied: docopt>=0.6.2 in c:\python39\lib\site-packages (from sourcedefender->insomniac) (0.6.2)
Requirement already satisfied: TgCrypto>=1.2.2 in c:\python39\lib\site-packages (from sourcedefender->insomniac) (1.2.2)
Requirement already satisfied: requests>=2.20.0 in c:\python39\lib\site-packages (from sourcedefender->insomniac) (2.25.1)
Requirement already satisfied: environs>=9.3.2 in c:\python39\lib\site-packages (from sourcedefender->insomniac) (9.3.2)
Requirement already satisfied: boltons>=21.0.0 in c:\python39\lib\site-packages (from sourcedefender->insomniac) (21.0.0)
Requirement already satisfied: msgpack>=1.0.2 in c:\python39\lib\site-packages (from sourcedefender->insomniac) (1.0.2)
Requirement already satisfied: pendulum>=2.1.2 in c:\python39\lib\site-packages (from sourcedefender->insomniac) (2.1.2)
Requirement already satisfied: python-dotenv in c:\python39\lib\site-packages (from environs>=9.3.2->sourcedefender->insomniac) (0.18.0)
Requirement already satisfied: marshmallow>=2.7.0 in c:\python39\lib\site-packages (from environs>=9.3.2->sourcedefender->insomniac) (3.12.1)
Requirement already satisfied: pytzdata>=2020.1 in c:\python39\lib\site-packages (from pendulum>=2.1.2->sourcedefender->insomniac) (2020.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\python39\lib\site-packages (from requests>=2.20.0->sourcedefender->insomniac) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\python39\lib\site-packages (from requests>=2.20.0->sourcedefender->insomniac) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\python39\lib\site-packages (from requests>=2.20.0->sourcedefender->insomniac) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python39\lib\site-packages (from requests>=2.20.0->sourcedefender->insomniac) (1.26.4)
Requirement already satisfied: retry~=0.9 in c:\python39\lib\site-packages (from uiautomator2->insomniac) (0.9.2)
Requirement already satisfied: Deprecated~=1.2.6 in c:\python39\lib\site-packages (from uiautomator2->insomniac) (1.2.12)
Requirement already satisfied: Pillow in c:\users\eddiejag\appdata\roaming\python\python39\site-packages (from uiautomator2->insomniac) (8.2.0)
Requirement already satisfied: cached-property<2.0,>=1.5.1 in c:\python39\lib\site-packages (from uiautomator2->insomniac) (1.5.2)
Requirement already satisfied: lxml>=4.3 in c:\python39\lib\site-packages (from uiautomator2->insomniac) (4.6.3)
Requirement already satisfied: packaging~=20.3 in c:\python39\lib\site-packages (from uiautomator2->insomniac) (20.9)
Requirement already satisfied: progress~=1.3 in c:\python39\lib\site-packages (from uiautomator2->insomniac) (1.5)
Requirement already satisfied: logzero~=1.5 in c:\python39\lib\site-packages (from uiautomator2->insomniac) (1.7.0)
Requirement already satisfied: whichcraft in c:\python39\lib\site-packages (from uiautomator2->insomniac) (0.6.1)
Requirement already satisfied: adbutils<1.0,>=0.11.0 in c:\python39\lib\site-packages (from uiautomator2->insomniac) (0.11.0)
Requirement already satisfied: apkutils2<2.0,>=1.0.0 in c:\python39\lib\site-packages (from adbutils<1.0,>=0.11.0->uiautomator2->insomniac) (1.0.0)
Requirement already satisfied: deprecation<3.0,>=2.0.6 in c:\python39\lib\site-packages (from adbutils<1.0,>=0.11.0->uiautomator2->insomniac) (2.1.0)
Requirement already satisfied: cigam in c:\python39\lib\site-packages (from apkutils2<2.0,>=1.0.0->adbutils<1.0,>=0.11.0->uiautomator2->insomniac) (0.0.3)
Requirement already satisfied: pyelftools in c:\python39\lib\site-packages (from apkutils2<2.0,>=1.0.0->adbutils<1.0,>=0.11.0->uiautomator2->insomniac) (0.27)
Requirement already satisfied: xmltodict in c:\python39\lib\site-packages (from apkutils2<2.0,>=1.0.0->adbutils<1.0,>=0.11.0->uiautomator2->insomniac) (0.12.0)
Requirement already satisfied: wrapt<2,>=1.10 in c:\python39\lib\site-packages (from Deprecated~=1.2.6->uiautomator2->insomniac) (1.12.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\python39\lib\site-packages (from packaging~=20.3->uiautomator2->insomniac) (2.4.7)
Requirement already satisfied: py<2.0.0,>=1.4.26 in c:\python39\lib\site-packages (from retry~=0.9->uiautomator2->insomniac) (1.10.0)
Requirement already satisfied: decorator>=3.4.2 in c:\python39\lib\site-packages (from retry~=0.9->uiautomator2->insomniac) (5.0.9)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python39\lib\site-packages)

However, Insomniac is still on 3.7.13 when I run it next.
