### ISSUE TITLE
Switching did not work FollowersFollowingListView *(BUG)

### ISSUE THREAD

**Issue by rusellned** [alexal1/Insomniac#355]
Hello, switching between tabs did not work when I had common friends. I Changed the values in "textContains" "Followers" "Following" to small letters. 

It seems to me that the tab switch has not worked for a couple of weeks after the instagram update, because if you did not have mutual friends, subscribers were opened by default.

**Comment by alexal1** [comment]
Thanks!

**Comment by alexal1** [comment]
Duplicate of #353
