### ISSUE TITLE
Cannot get username - crash at start

### ISSUE THREAD

**Issue by Patryk803** [alexal1/Insomniac#356]
[Crash-2021-06-24-08-12-21.zip](https://github.com/alexal1/Insomniac/files/6707082/Crash-2021-06-24-08-12-21.zip)

**Comment by alexal1** [comment]
You're using very old version. Upgrade to `v3.7.15` please

**Comment by Patryk803** [comment]
I have tried the last one using --upgrade and got the same error

**Comment by alexal1** [comment]
Then I'll need crash from the latest version

**Comment by Patryk803** [comment]
Hey,

Please find attached the crash with the latest version installed.

Thanks,
Patryk

**Comment by alexal1** [comment]
> Hey, Please find attached the crash with the latest version installed. Thanks, Patryk

No you didn't

**Comment by Patryk803** [comment]
Hey,

What do you mean? Isn't the version latest? How do I upgrade to latest one
then? I used --upgrade

**Comment by alexal1** [comment]
I mean that you didn't attach crash folder. Please do it in github: https://github.com/alexal1/Insomniac/issues/356

**Comment by Patryk803** [comment]
[Crash-2021-06-24-12-11-27.zip](https://github.com/alexal1/Insomniac/files/6708893/Crash-2021-06-24-12-11-27.zip)

**Comment by alexal1** [comment]
> Crash-2021-06-24-12-11-27.zip

As you can see in the first line of the log, it's still v3.6.6

**Comment by Patryk803** [comment]
Hmm. Any other way of upgrading it?
I did python -m pip install insomniac --upgrade

**Comment by alexal1** [comment]
> Hmm. Any other way of upgrading it? I did python -m pip install insomniac --upgrade
> […](#)

Just wrote an explanation of how to update: https://insomniac-bot.com/docs/#/how-to-update
