### ISSUE TITLE
Uiautomator error on _iterate_over_followers

### ISSUE THREAD

**Issue by michaelmagro** [alexal1/Insomniac#36]
This happens randomly, when it happens it automatically resumes the session. MacOS Catalina. Huawei P30 PRO. 

![Captura de Tela 2020-06-27 às 23 45 18](https://user-images.githubusercontent.com/6068710/85940722-83251d00-b8f4-11ea-8bb3-6e04ff6f91d3.png)

Screenshot:
![Crash-2020-06-27-23-43-39](https://user-images.githubusercontent.com/6068710/85941192-c5039280-b8f7-11ea-9dda-7b03e0e87832.png)

**Comment by alexal1** [comment]
Sooo the problem is that the script thinks that it's on the followers list, but actually it's in someone's profile. Don't know why yet. Did you mention something strange in its behavior?

**Comment by alexal1** [comment]
At least "Less than 6 photos" phrase is strange as here are more than 6 photos

**Comment by Foncekar** [comment]
> 
> 
> At least "Less than 6 photos" phrase is strange as here are more than 6 photos

latency which would make the photos not yet visible at the time ?

**Comment by michaelmagro** [comment]
Still occurring, version v1.6.1

![Captura de Tela 2020-06-29 às 14 34 33](https://user-images.githubusercontent.com/6068710/86037713-320d4a00-ba16-11ea-8fca-b4c9dd9d98ce.png)



![Crash-2020-06-29-14-33-43](https://user-images.githubusercontent.com/6068710/86037696-2752b500-ba16-11ea-89c7-522e8153937d.png)

**Comment by alexal1** [comment]
Look, as I see something strange happens _before_ the crash. It failed following, probably because wrong screen was opened at that time. And then after "Back to followers list" it wasn't on followers list actually. Try to figure out when exactly the script goes wrong.

Maybe it opens something which mustn't (IGTV / Story)?

**Comment by michaelmagro** [comment]
In some cases where the same error happened, I realized that he really clicked to watch a story and in other cases he clicked on the comment list of a photo and stood on the screen (there is an error). My device is a Huawei P30 PRO, the screen is large and has rounded edges (**6.47 inches, 1080 x 2340 pixels, 19.5: 9 ratio (~ 398 ppi density)**), can the screen size be generating these errors? Because I don't see other people complaining about the same mistake ..

![huawei-p30-pro-3](https://user-images.githubusercontent.com/6068710/86502530-9f084300-bd7a-11ea-8b7f-aea40ea76486.jpg)

**Comment by michaelmagro** [comment]
I found a solution to the problem: increase the text and display size on Android, so the buttons get bigger and the bot can interact much better, without errors now.

Config:
![WhatsApp Image 2020-07-09 at 11 05 27](https://user-images.githubusercontent.com/6068710/87050250-64683580-c1d4-11ea-80a2-9afd1d299b55.jpeg)

Result:
![WhatsApp Image 2020-07-09 at 11 05 27 (1)](https://user-images.githubusercontent.com/6068710/87050292-7053f780-c1d4-11ea-8edf-aac2085566eb.jpeg)
