### ISSUE TITLE
Crash on unfollowing v3.7.18

### ISSUE THREAD

**Issue by nxzoo** [alexal1/Insomniac#360]
[Crash-2021-07-07-03-17-08.zip](https://github.com/alexal1/Insomniac/files/6773577/Crash-2021-07-07-03-17-08.zip)
[Crash-2021-07-07-03-15-20.zip](https://github.com/alexal1/Insomniac/files/6773574/Crash-2021-07-07-03-15-20.zip)

**Comment by felipe4334** [comment]
https://github.com/alexal1/Insomniac/pull/370
