### ISSUE TITLE
Crash in v3.7.20 in profile page

### ISSUE THREAD

**Issue by nxzoo** [alexal1/Insomniac#361]
In interact_target
[Crash-2021-07-08-23-36-33.zip](https://github.com/alexal1/Insomniac/files/6787406/Crash-2021-07-08-23-36-33.zip)

**Comment by SithX** [comment]
i have the same problem!
[Crash-2021-07-09-03-39-55.zip](https://github.com/alexal1/Insomniac/files/6789401/Crash-2021-07-09-03-39-55.zip)

**Comment by alexal1** [comment]
Fixed in v21
