### ISSUE TITLE
Crash on unfollowing v3.7.21

### ISSUE THREAD

**Issue by nxzoo** [alexal1/Insomniac#362]
[Crash-2021-07-10-03-43-10.zip](https://github.com/alexal1/Insomniac/files/6794472/Crash-2021-07-10-03-43-10.zip)

in flow
[Crash-2021-07-10-06-15-24.zip](https://github.com/alexal1/Insomniac/files/6794652/Crash-2021-07-10-06-15-24.zip)

**Comment by nxzoo** [comment]
bot tries to get back to list instead of confirm unfollowing

**Comment by DemonionFF** [comment]
same here

**Comment by DemonionFF** [comment]
as seems it is not going to fix itself, here is a fix I am using

version 3.7.21
in actions_impl.py

![Image 26 07 2021 at 21 45](https://user-images.githubusercontent.com/21122119/127049379-9a75df64-e536-4a0f-b9c6-f0128f7a07bc.jpg)

**Comment by nxzoo** [comment]
Thanks mate
