### ISSUE TITLE
Consistently crashing upon interaction

### ISSUE THREAD

**Issue by LukaRGB** [alexal1/Insomniac#366]
Running on Windows 10, Python 3.9, Bluestacks 5
I consistently get this error when it tries to like a photo. I've tried reinstalling everything. I've tried using "--old" for uiautomator and nothing.
`Exception: -32001 Jsonrpc error: <java.lang.NullPointerException> data: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference `
The first time it runs, I also get this error once: 
`com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner] uiautomator2.GatewayError(gateway error, time used 0.0s): `

Log files:
[insomniac_log-2021-07-18-18-38-00.log](https://github.com/alexal1/Insomniac/files/6874595/insomniac_log-2021-07-18-18-38-00.log)
[insomniac_log-2021-07-18-17-56-34.log](https://github.com/alexal1/Insomniac/files/6874594/insomniac_log-2021-07-18-17-56-34.log)

@alexal1

**Comment by alexal1** [comment]
Hmm I'd recommend to update pip and uiautomator. Then uninstall ATX app on your device and try again. If doesn't help, try on another device: this seems to be a problem with connecting to a device
