### ISSUE TITLE
Hangs at PROFILE... 

### ISSUE THREAD

**Issue by shippie** [alexal1/Insomniac#369]
Version 3.7.23.1 hangs at 

Didn't find tab PROFILE in the tab bar... Maybe English language is not set!?

But English language is set.

Version 3.7.16 has no problem to open the profile page.

[Crash-2021-08-01-21-21-19.zip](https://github.com/alexal1/Insomniac/files/6915302/Crash-2021-08-01-21-21-19.zip)

**Comment by Baghodlr** [comment]
> Version 3.7.23.1 hangs at
> 
> Didn't find tab PROFILE in the tab bar... Maybe English language is not set!?
> 
> But English language is set.
> 
> Version 3.7.16 has no problem to open the profile page.
> 
> [Crash-2021-08-01-21-21-19.zip](https://github.com/alexal1/Insomniac/files/6915302/Crash-2021-08-01-21-21-19.zip)

What version if instagram are you running? I had similar issues with newer version if IG but per suggestions on the Discord downgrading to 196.X (on instagram, not the bot) and running the newest version of the bot fixed any problems I was having; using an emulator.

**Comment by shippie** [comment]
> > Version 3.7.23.1 hangs at
> > Didn't find tab PROFILE in the tab bar... Maybe English language is not set!?
> > But English language is set.
> > Version 3.7.16 has no problem to open the profile page.
> > [Crash-2021-08-01-21-21-19.zip](https://github.com/alexal1/Insomniac/files/6915302/Crash-2021-08-01-21-21-19.zip)
> 
> What version if instagram are you running? 
_>   I think the newest version...._

I had similar issues with newer version if IG but per suggestions on the Discord downgrading to 196.X (on instagram, not the bot) and running the newest version of the bot fixed any problems I was having; using an emulator.

_> I try to downgrade the Instagram app and upgrade the bot to the actual version. 
> Instagram run on a mobile phone, so I must downgrade manually.
> Thanks for the recommendation_

**Comment by Ever-92** [comment]
[Crash-2021-08-15-22-44-42.zip](https://github.com/alexal1/Insomniac/files/6989655/Crash-2021-08-15-22-44-42.zip)

I have the same Problem...

**Comment by alexal1** [comment]
Please downgrade to latest supported IG version: https://insomniac-bot.com/get_latest_supported_ig_apk/.
It's too much work to support every new IG version, while we can concentrate on new features instead.
