### ISSUE TITLE
Can't find "Account" Tab

### ISSUE THREAD

**Issue by yurilimajr** [alexal1/Insomniac#375]
Even when using the supported IG version (195...) as labeled upon starting the script, the bot does not recognize the new button on IG search and can't find the "account" tab and so on, can't interact with the @ or #.

**Comment by alexal1** [comment]
Well we need a dump (UI + hierarchy) to sort this out. Please put [this file](https://gist.github.com/alexal1/5690d14b4461e3b52539438ac98c0151) in the same folder where start.py is. Then open a screen with the issue and run `python dump.py`.

**Comment by yurilimajr** [comment]
Solved! Thanks
