### ISSUE TITLE
Can't update v3.7.12

### ISSUE THREAD

**Issue by yondermann** [alexal1/Insomniac#381]
Hi, I run version 3.7.12 and every time I start I get this message:
Insomniac v3.7.12
Newer version is available (v3.7.28). Please run
python3 -m pip install insomniac --upgrade

I run the command I get this:
pi@raspberrypi:~/Tools/Insomniac $ python3 -m pip install insomniac --upgrade

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting insomniac
  Downloading https://files.pythonhosted.org/packages/e4/fe/ead3d64401a0b47175321eeb26ba96fb808c464c98cb7b4077e6a4ef4fef/insomniac-3.7.28-py3-none-any.whl (2.1MB)
    100% |████████████████████████████████| 2.1MB 140kB/s 
Requirement already satisfied, skipping upgrade: sourcedefender in /home/pi/.local/lib/python3.7/site-packages (from insomniac) (7.1.6)
Requirement already satisfied, skipping upgrade: colorama in /usr/lib/python3/dist-packages (from insomniac) (0.3.7)
Requirement already satisfied, skipping upgrade: uiautomator2 in /home/pi/.local/lib/python3.7/site-packages (from insomniac) (2.16.0)
Requirement already satisfied, skipping upgrade: croniter in /home/pi/.local/lib/python3.7/site-packages (from insomniac) (1.0.13)
Requirement already satisfied, skipping upgrade: uiautomator in /home/pi/.local/lib/python3.7/site-packages (from insomniac) (1.0.2)
Requirement already satisfied, skipping upgrade: peewee in /home/pi/.local/lib/python3.7/site-packages (from insomniac) (3.14.4)
Requirement already satisfied, skipping upgrade: environs>=9.3.2 in /home/pi/.local/lib/python3.7/site-packages (from sourcedefender->insomniac) (9.3.2)
Requirement already satisfied, skipping upgrade: docopt>=0.6.2 in /home/pi/.local/lib/python3.7/site-packages (from sourcedefender->insomniac) (0.6.2)
Requirement already satisfied, skipping upgrade: boltons>=21.0.0 in /home/pi/.local/lib/python3.7/site-packages (from sourcedefender->insomniac) (21.0.0)
Requirement already satisfied, skipping upgrade: requests>=2.20.0 in /usr/lib/python3/dist-packages (from sourcedefender->insomniac) (2.21.0)
Requirement already satisfied, skipping upgrade: TgCrypto>=1.2.2 in /home/pi/.local/lib/python3.7/site-packages (from sourcedefender->insomniac) (1.2.2)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.8.1 in /home/pi/.local/lib/python3.7/site-packages (from sourcedefender->insomniac) (2.8.1)
Requirement already satisfied, skipping upgrade: msgpack>=1.0.2 in /home/pi/.local/lib/python3.7/site-packages (from sourcedefender->insomniac) (1.0.2)
Requirement already satisfied, skipping upgrade: retry~=0.9 in /home/pi/.local/lib/python3.7/site-packages (from uiautomator2->insomniac) (0.9.2)
Requirement already satisfied, skipping upgrade: adbutils<1.0,>=0.11.0 in /home/pi/.local/lib/python3.7/site-packages (from uiautomator2->insomniac) (0.11.0)
Requirement already satisfied, skipping upgrade: packaging~=20.3 in /home/pi/.local/lib/python3.7/site-packages (from uiautomator2->insomniac) (20.9)
Requirement already satisfied, skipping upgrade: logzero~=1.5 in /home/pi/.local/lib/python3.7/site-packages (from uiautomator2->insomniac) (1.7.0)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python3/dist-packages (from uiautomator2->insomniac) (1.12.0)
Requirement already satisfied, skipping upgrade: Deprecated~=1.2.6 in /home/pi/.local/lib/python3.7/site-packages (from uiautomator2->insomniac) (1.2.12)
Requirement already satisfied, skipping upgrade: lxml>=4.3 in /usr/lib/python3/dist-packages (from uiautomator2->insomniac) (4.3.2)
Requirement already satisfied, skipping upgrade: cached-property<2.0,>=1.5.1 in /home/pi/.local/lib/python3.7/site-packages (from uiautomator2->insomniac) (1.5.2)
Requirement already satisfied, skipping upgrade: whichcraft in /home/pi/.local/lib/python3.7/site-packages (from uiautomator2->insomniac) (0.6.1)
Requirement already satisfied, skipping upgrade: Pillow in /usr/lib/python3/dist-packages (from uiautomator2->insomniac) (5.4.1)
Requirement already satisfied, skipping upgrade: progress~=1.3 in /home/pi/.local/lib/python3.7/site-packages (from uiautomator2->insomniac) (1.5)
Requirement already satisfied, skipping upgrade: urllib3>=1.7.1 in /usr/lib/python3/dist-packages (from uiautomator->insomniac) (1.24.1)
Requirement already satisfied, skipping upgrade: python-dotenv in /home/pi/.local/lib/python3.7/site-packages (from environs>=9.3.2->sourcedefender->insomniac) (0.17.1)
Requirement already satisfied, skipping upgrade: marshmallow>=2.7.0 in /home/pi/.local/lib/python3.7/site-packages (from environs>=9.3.2->sourcedefender->insomniac) (3.12.1)
Requirement already satisfied, skipping upgrade: py<2.0.0,>=1.4.26 in /home/pi/.local/lib/python3.7/site-packages (from retry~=0.9->uiautomator2->insomniac) (1.10.0)
Requirement already satisfied, skipping upgrade: decorator>=3.4.2 in /usr/lib/python3/dist-packages (from retry~=0.9->uiautomator2->insomniac) (4.3.0)
Requirement already satisfied, skipping upgrade: apkutils2<2.0,>=1.0.0 in /home/pi/.local/lib/python3.7/site-packages (from adbutils<1.0,>=0.11.0->uiautomator2->insomniac) (1.0.0)
Requirement already satisfied, skipping upgrade: deprecation<3.0,>=2.0.6 in /home/pi/.local/lib/python3.7/site-packages (from adbutils<1.0,>=0.11.0->uiautomator2->insomniac) (2.1.0)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /usr/lib/python3/dist-packages (from packaging~=20.3->uiautomator2->insomniac) (2.2.0)
Requirement already satisfied, skipping upgrade: wrapt<2,>=1.10 in /usr/lib/python3/dist-packages (from Deprecated~=1.2.6->uiautomator2->insomniac) (1.10.11)
Requirement already satisfied, skipping upgrade: xmltodict in /home/pi/.local/lib/python3.7/site-packages (from apkutils2<2.0,>=1.0.0->adbutils<1.0,>=0.11.0->uiautomator2->insomniac) (0.12.0)
Requirement already satisfied, skipping upgrade: pyelftools in /home/pi/.local/lib/python3.7/site-packages (from apkutils2<2.0,>=1.0.0->adbutils<1.0,>=0.11.0->uiautomator2->insomniac) (0.27)
Requirement already satisfied, skipping upgrade: cigam in /home/pi/.local/lib/python3.7/site-packages (from apkutils2<2.0,>=1.0.0->adbutils<1.0,>=0.11.0->uiautomator2->insomniac) (0.0.3)
Installing collected packages: insomniac
  Found existing installation: insomniac 3.7.25
    Uninstalling insomniac-3.7.25:
      Successfully uninstalled insomniac-3.7.25
Successfully installed insomniac-3.7.28

Then I start insomniac again and I get the same:
Insomniac v3.7.12
Newer version is available (v3.7.28). Please run
python3 -m pip install insomniac --upgrade

Why is this happening and what should I do?

**Comment by alexal1** [comment]
https://insomniac-bot.com/docs/#/how-to-update

**Comment by yondermann** [comment]
I've been trying to force reinstall 3.7.28 but I've got this error:

 Complete output from command python setup.py egg_info:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-5j5b3tre/pendulum/setup.py'

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5j5b3tre/pendulum/
