### ISSUE TITLE
 No username, so the script won't read/write from the database

### ISSUE THREAD

**Issue by stateclata** [alexal1/Insomniac#393]
So, the script was running perfectly until yesterday 06/10/2021. Since then I keep getting the error " No username, so the script won't read/write from the database" as soon as I run the script. I definitely have the latest version. 

Screenshot: 
https://i.ibb.co/9ytZDBg/insomniac-username-error.png

The crash file:
[Crash-2021-10-07-15-54-48.zip](https://github.com/alexal1/Insomniac/files/7303482/Crash-2021-10-07-15-54-48.zip)

**Comment by jacekmichalski** [comment]
I have exactly the same issue. How to fix it?

**Comment by stateclata** [comment]
> Same issue for me. IG version (208.0.0.32.135).
>  Ive also tried lower versions but they instantly crash on my emulator (Android-x86)
> 
> > yo, my bad. Anyway I got another bot working, thanks thought!
> 
>  @stateclata can you provide the name of the bot ?

"gramAddict"

**Comment by alexal1** [comment]
We support only 195.0.0.31.123 IG version, that's absolutely right. Strange that it crashes on your emulator, I can dig into this if you write me and provide some details t.me/alexal1
