### ISSUE TITLE
Instagram app v.195.0.0.31.123 non stop crashing

### ISSUE THREAD

**Issue by TiagoDS7** [alexal1/Insomniac#402]
Instagram app v.195.0.0.31.123 non stop crashing on MEmu after first session finished, only way to circumvent this is to erase App data, but after next session loop is finished, the issue repeats itself. 
Any clue on why this is happening? 😕
![image](https://user-images.githubusercontent.com/41171767/140934737-edd48f48-5e2b-4887-8108-6d136c32cea3.png)

**Comment by JunjieC27** [comment]
Hey I got the same issue,
How did u get rid of it?
