### ISSUE TITLE
can you help me ith the below please ? latest insomniac

### ISSUE THREAD

**Issue by roncam82** [alexal1/Insomniac#405]
raise AttributeError(
AttributeError: 'Session or Device' object has no attribute '_is_alive'

[11/20 15:34:20] Could not save crash after an error. Crash-save-error: 'Session or Device' object has no attribute '_is_alive'
[11/20 15:34:20] Error - 'Session or Device' object has no attribute '_is_alive'

**Comment by shifenis** [comment]
Try with the flag `--old`, i think is a just a workaround

**Comment by Polkyanik** [comment]
pip install --upgrade pip
pip install --upgrade uiautomator2
(Y)

**Comment by gtcdevop** [comment]
@shifenis  Why does this happen? any change happened on _uiautomator2_ api? Regardless you fix worked
@Polkyanik  Tried that, didn`t work

**Comment by alexal1** [comment]
Fixed in v3.8.2
