### ISSUE TITLE
FEATURE: Filter users by their amount of followers and following to better target audience

### ISSUE THREAD

**Issue by dwai03** [alexal1/Insomniac#42]
# Story
As a user of this app, I want to be able to get analytics of people that I could potentially follow so that the app can filter out whether or not the person is worth following.  Specifically the new requested data point is around a bloggers a follower count, following count, and follower/following ratio.

Issue:
Not sure how the app is currently identifing elements from the app.  Currently need to understand how the elements are all selected/identified then will be able to implement the code.

**Comment by alexal1** [comment]
This feature is already implemented, but is available for patrons only: https://www.patreon.com/posts/38826184.
Thanks for mentioning, I will add this to the FAQ section.

**Comment by pynner** [comment]
t
