### ISSUE TITLE
detection of DEEP LINK

### ISSUE THREAD

**Issue by instasck** [alexal1/Insomniac#438]
I see we open the links using the deep links in ADB.
Can Instagram detect the referrer to the app ? which is ADB...

https://stackoverflow.com/questions/47161195/get-correct-referrer-application-on-deep-linking

**Comment by alexal1** [comment]
> Can Instagram detect the referrer to the app ? which is ADB...

No, don't think so. Deep link is still just a link. The only difference is that it can be handled by the app, not only browser. It contains only information which you see. So if there's not something like `&regerrer=adb` in it then how can app assume that referrer is adb?

**Comment by instasck** [comment]
getReferrer will return it.
I guess it will say system something ...
better open the link in chrome and click on it over there
