### ISSUE TITLE
Pullrequests not allowed? 

### ISSUE THREAD

**Issue by GitNees** [alexal1/Insomniac#46]
I see a nice pullrequest from 3 days ago for hashtag support!

Thx @dwai03 

I tested it and works! Why isn't it been pulled?

Thats how instapy got big, community! I do see updates from today, but pullrequests being ingored?

**Comment by dwai03** [comment]
Still few kinks to be worked out, but predominately works.

**Comment by GitNees** [comment]
Indeed, some strange thing going on that it stops after just a few interaction.
Also, would make more sense, when it liked the picture from the hashtag, then goes to the profile and likes some 1 or 2 more (or none) as thats more human like.

But i guess you need to update your code with the lastest version, als I had to copy paste some additional code to make it work fully with the latests files.

**Comment by alexal1** [comment]
@GitNees Pull Requests are appreciated of course!
@dwai03 does a great thing, I'm just not very quick to make comments, and that PR still needs some additional work.
Why don't discuss everything about that PR in [PR's comments](https://github.com/alexal1/Insomniac/pull/45)?
