### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by xerZV** [alexal1/Insomniac#5]
Could you please provide some quickstart example?
Where to put acc and pass?

**Comment by alexal1** [comment]
There's no need in acc and pass. No need in `quickstart.py` too.

This script simply sends touch events to your phone/tablet, where Instagram app is running. It presses buttons just like you would. So, instead of providing acc and pass just connect device to your computer.

In InstaPy you launch `quickstart.py`, here you launch `insomniac.py`. You can find detailed information on how to launch on the main page.

**Comment by xerZV** [comment]
Ah, I see. Will give a try. Thank you

**Comment by xerZV** [comment]
Running on raspberry pi 4 and getting this error:
```
pi@:~/Library/Android/sdk/platform-tools $ ./adb devices
bash: ./adb: cannot execute binary file: Exec format error
```

Any suggestions?

**Comment by xerZV** [comment]
Nvm, I got it.
`https://askubuntu.com/questions/710426/android-sdk-on-ubuntu-32bit`

**Comment by xerZV** [comment]
@alexal1 
![image](https://user-images.githubusercontent.com/23699044/83967577-97fd2a80-a8cb-11ea-9c29-24cfc562982c.png)

**Comment by xerZV** [comment]
I changed this
`import uiautomator`
with this 
`from uiautomator import device as d`

Then commented line #33
`#device = uiautomator.device`
and renamed `device` to `d` in your script.

Now I have a progress but still getting errors:
![image](https://user-images.githubusercontent.com/23699044/83968126-b2390780-a8cf-11ea-930c-c5c58f3eef70.png)

**Comment by alexal1** [comment]
Pls check `python --version`
My output is `Python 2.7.16`. For now the script works on Python 2.
I think you've installed `uiautomator` for Python 3 only.

**Comment by xerZV** [comment]
![image](https://user-images.githubusercontent.com/23699044/83974117-86c81400-a8f3-11ea-84ee-377191e5f1ba.png)

**Comment by xerZV** [comment]
Oh, my `pip` was pointing to `python 3` instead of `python 2` so I had to use specifically `pip2 install uiautomator`

**Comment by alexal1** [comment]
@xerZV since of `v1.2.3` the script works on Python 3. I did the migration today for everybody's convenience.

**Comment by xerZV** [comment]
@alexal1 Nice. I tried it today and it works like a charm! I'm not a python dev but looking forward to learn it so maybe I will fork it and try to improve it somehow.

**Comment by alexal1** [comment]
@xerZV glad to hear that, feel free to make PRs too :)
