### ISSUE TITLE
custom sleep function ?

### ISSUE THREAD

**Issue by potentowl** [alexal1/Insomniac#55]
first time running and it goes fast sure it wont get blocked? anyway to add a custom sleep function ?

**Comment by alexal1** [comment]
Feel free to change it in `utils.py` > `def random_sleep():`.
These delays are quite human-like now, don't see why Instagram would block because of them. It's better to care about limits and how long Instagram app is kept opened.

**Comment by Ardy000** [comment]
Can't find `random_sleep()`

**Comment by Ardy000** [comment]
Nevermind. Found it.

It is now in sleeper.py
