### ISSUE TITLE
"Running Insomniac with two or more actions is not supported yet."

### ISSUE THREAD

**Issue by jduhautois** [alexal1/Insomniac#56]
I can't seem to enter the right arguments to make unfollowing work. I keep receiving the error "Running Insomniac with two or more actions is not supported yet." Could you please help?

I have the following arguments and run the following command

Command:
python insomniac.py --unfollow-non-followers 100

Arguments:
parser.add_argument('--interact',
nargs='+',
help='list of usernames with whose followers you want to interact',
metavar=(''),
default=[''])
parser.add_argument('--likes-count',
help='number of likes for each interacted user, 2 by default',
metavar='',
default=0)
parser.add_argument('--total-likes-limit',
help='limit on total amount of likes during the session, 1000 by default',
metavar='',
default=0)
parser.add_argument('--interactions-count',
help='number of interactions per each blogger, 100 by default',
metavar='',
default=0)
parser.add_argument('--repeat',
help='repeat the same session again after N minutes after completion, disabled by default',
metavar='')
parser.add_argument('--follow-percentage',
help='follow given percentage of interacted users, 0 by default',
metavar='',
default=0)
parser.add_argument('--unfollow',
help='unfollow at most given number of users. Only users followed by this script will '
'be unfollowed. The order is from oldest to newest followings',
metavar='',
default='0')
parser.add_argument('--unfollow-non-followers',
help='unfollow at most given number of users, that don't follow you back. Only users followed '
'by this script will be unfollowed. The order is from oldest to newest followings',
metavar='100',
default='100')

**Comment by alexal1** [comment]
That's strange, didn't you change the code?

**Comment by alexal1** [comment]
Not enough information, closing now.

`python insomniac.py --unfollow-non-followers 100` is a valid command, must work.
