### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by quintendewilde** [alexal1/Insomniac#57]
[07/14 19:54:31] Open Instagram app
[07/14 19:54:33] Sleep for 2 seconds
[07/14 19:54:35] Press profile
[07/14 19:54:42] Failed to get username
Traceback (most recent call last):
  File "insomniac.py", line 369, in <module>
    main()
  File "insomniac.py", line 81, in main
    storage = Storage(session_state.my_username)
  File "/home/pi/Insomniac/src/storage.py", line 17, in __init__
    os.makedirs(my_username)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by lucianoshl** [comment]
same here

**Comment by alexal1** [comment]
@quintendewilde @lucianoshl thanks for reporting, check on this branch please https://github.com/alexal1/Insomniac/tree/fix_no_such_file_or_directory

**Comment by quintendewilde** [comment]
How do I combine this with my code?

**Comment by alexal1** [comment]
@quintendewilde seems that the script cannot read your username from the profile screen. Probably you have different UI in your app. Are you sure that you've got the latest Instagram version? If yes, could you do a `uiautomatorviewer` screenshot and attach it here?

> How do I combine this with my code?

Please don't mix the code with yours while we're debugging: I can't debug the code I don't see.

**Comment by quintendewilde** [comment]
How do I achieve this uiautomatorviewer screenshot on raspberry pi or mac? 
Because I have no windows available.

**Comment by alexal1** [comment]
I will create post about using **uiautomatorviewer** soon.
As I understood, updating Instagram solved the problem?
