### ISSUE TITLE
Issue with jump starting the script

### ISSUE THREAD

**Issue by pxp920** [alexal1/Insomniac#62]
Hello,

I am having issues getting the script to run.  I believe I've done all the steps, but when I try to run the Python script it will not produce any outcome.

-Developer enables
-Stay awake enabled
-USB Debugging enabled
-uiautomator/colorama installed
-android platform tools installed and added to PATH

Any pointers will be much appreciated on what I'm omitting/not doing properly (I use Windows and I typically don't use an Android so please bear with me)

![3](https://user-images.githubusercontent.com/30659989/87867324-d9b4d280-c959-11ea-8082-0e20aa870100.PNG)
![2](https://user-images.githubusercontent.com/30659989/87867326-dd485980-c959-11ea-89cc-63f1493a426d.PNG)

**Comment by alexal1** [comment]
Seems that your Python is not working properly. You can check this by launching this simple script (unzip first).
[hello.py.zip](https://github.com/alexal1/Insomniac/files/4943420/hello.py.zip)

**Comment by pxp920** [comment]
Thanks @alexal1 -- that issue was as simple (and dumb) as that.  I rarely run code via cmd and did not remember that my python executable was python instead of python3. 

If I can bother you for a follow up issue, I am getting this error now:
![image](https://user-images.githubusercontent.com/30659989/87877278-6045d000-c9ab-11ea-9f84-098ec2ca7c87.png)
