### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by shurco** [alexal1/Insomniac#65]
Did you plan to add SQLite support?

**Comment by alexal1** [comment]
No, why?
That will require installing additional package for everyone. And nobody complained on using JSON yet.

**Comment by shurco** [comment]
Protect against duplicate actions.

**Comment by alexal1** [comment]
> Protect against duplicate actions.

What actions?

**Comment by shurco** [comment]
For example:
1. Protection against re-adding to friends after deletion
2. Re-like on the photo
etc.

**Comment by alexal1** [comment]
> Protection against re-adding to friends after deletion

Already implemented. Script doesn't follow users with "following_status": "UNFOLLOWED". Such status assigns to users who were followed -> unfollowed by the script.

> Re-like on the photo

This can be implemented, but better create a separate issue for this feature with "enhancement" label.

Generally speaking, SQLite and JSON are just the ways of storing data. Logic you speaking about can be implemented on every storage.
