### ISSUE TITLE
Crash when back to profile

### ISSUE THREAD

**Issue by GeikoHub** [alexal1/Insomniac#66]
Script crashes as often as it tries to get back to home and like a pic on the wall before going back to follower interactions.

Don't know really why but happens each session.
Maybe something due to screen size again with old android version (5.0.2) ?
(on Galaxy core prime SM-G360F)

![Crash-2020-07-23-16-19-11](https://user-images.githubusercontent.com/66672318/88310109-92d72c00-cd0f-11ea-88f1-0de20b4aa167.png)
![Capture](https://user-images.githubusercontent.com/66672318/88310117-94a0ef80-cd0f-11ea-8494-4c4fedae818f.JPG)

**Comment by alexal1** [comment]
Probably fixed in `v2.0.0`, please reopen if it's not.
