### ISSUE TITLE
Update and preserve interactions

### ISSUE THREAD

**Issue by Eimuex** [alexal1/Insomniac#67]
Sorry if this question is not suitable for github, but I would like to know how to update to latest version and still keep list of interacted users? Is it enough to backup profile name folder and paste it to new git cloned folder? Thank you

**Comment by GeikoHub** [comment]
just download the zip file, then extract it.
And replace the files in without erasing the old folder.
For me i lose some settings in the insomniac.py but list of interacted and others things are kept ;)

**Comment by Eimuex** [comment]
Thanks
