### ISSUE TITLE
Unfollow non-followers problem

### ISSUE THREAD

**Issue by Eimuex** [alexal1/Insomniac#69]
Since update to last version my bot is struggling to find non-followers. It clicks on so many profiles until instagram starts to throw error 'please wait few minutes' and then bot start to unfollow followers because page is not loaded and can't read the status I guess. Maybe has to do something with latest #53 fix? Anyone got similar issue?

**Comment by Eimuex** [comment]
UPDATE: It seems that followed list on the phone loads first 50 (or so) users again and again - falls into loop. I should swipe it manually to load new ones. Clear cache didn't help. Is it possible for bot to sort the list from latest followed instead of earliest?

**Comment by alexal1** [comment]
That's a huge problem. I know about these loops, got them while scrolling manually. We have to think how to solve this.
> I have to swipe it manually to load new ones

So, when you swipe manually it goes out of the loop? What's the difference between your swipe and programmatic?

> Maybe has to do something with latest #53 fix?

Nope, that fix was about interaction with bloggers, here we have unfollowing, that's completely another part of the algorithm.

**Comment by Eimuex** [comment]
> So, when you swipe manually it goes out of the loop? What's the difference between your swipe and programmatic?
Manually I swipe one huge chunk right after bot sorts the list, it works without problem after that.

**Comment by alexal1** [comment]
Okaaay, I'll add some checking for a loop and a huge scroll after that, let's see if it helps

**Comment by Eimuex** [comment]
I think it refresh the list when reach bottom of loaded users fast. It stops for a second, loading circle shows up and new users are loaded. So maybe when loop occurs it should swipe to the bottom instantly, dunno. Thank you for your effort and being responsive. Cheers

**Comment by gvmturl** [comment]
Hello guys! Is it solved?

**Comment by pixelicous** [comment]
Just ran into the same problem..

**Comment by Fadude** [comment]
Fixed on v3.5.7 using Soft-ban-indicator (wont continue to run after 5 empty-lists / empty-profiles)
