### ISSUE TITLE
No interaction

### ISSUE THREAD

**Issue by GeikoHub** [alexal1/Insomniac#7]
The bot works like a charm, in the state of work in progress that's a really good begining.
Maybe a video/notice is needed to really understand how to install and make it works.

In my case, the bot interact with other profiles but don't put any like,
it's just go on the profile, check it, scroll down and come back to followers list
![Capture](https://user-images.githubusercontent.com/66672318/84132227-eafaed00-aa45-11ea-81b7-1e795219bc99.JPG)

**Comment by alexal1** [comment]
As I see it says that "Less than 6 photos / account is private. Skip user."
Bot is guaranteed to interact only with public accounts with >= 6 posts.

**Comment by GeikoHub** [comment]
yep, attached file was to show the launch.
The 1st ones you're right doesn't fit the bot rules.

I ran it for about 4h yesterday and 2h this morning without any like on any profile.
Tried to change the rules too yesterday, and run today with the update and default settings.

But nothing change, no interaction ^^"

**Comment by alexal1** [comment]
That's strange, there at least should be some errors in the log. Could you please attach log with the case of wrong non-interacting?

**Comment by GeikoHub** [comment]
i launch it back and let it run.
Post that when there's more report to show ;)

**Comment by GeikoHub** [comment]
it seems now (yesterday i changed the inetraction at least 6 pics for 1 pics)
That "private or public account", "more or less than 6 pics" or every account just considered as skip
Every account done that case under;
--------------
Back to followers list
_<@sven_*********>_ : interact
Sleep for 3 seconds
Open and like photo #1 (1 row, 1 column)
[93mProbably need to scroll.[0m
[93mLess than 6 photos / account is private. Skip user.[0m
-----------------
![Capture](https://user-images.githubusercontent.com/66672318/84135735-9c038680-aa4a-11ea-96ec-b0b311b67a4e.JPG)

**Comment by alexal1** [comment]
Let's consider "@lionyzion" user for example. I see that it has enough posts but script skips it. Could you please send some screenshots of this profile made from the device on which you run the script?

**Comment by GeikoHub** [comment]
as that?!
Tested on a old one android
Samsung galaxy core prime - SM-G360f
Android version 5.0.2
![IMG_20200609_123254](https://user-images.githubusercontent.com/66672318/84137977-d02c7680-aa4d-11ea-8601-ad687f3c8a82.jpg)
![IMG_20200609_123246](https://user-images.githubusercontent.com/66672318/84138076-fc47f780-aa4d-11ea-9812-a92ea9218e85.jpg)

**Comment by alexal1** [comment]
Yes, thank you. When script prints "Probably need to scroll" while being on the profile, does scroll really happen?

**Comment by GeikoHub** [comment]
Yes it scroll for about half a screen down on every profile.
Every time the same scroll by the way.

**Comment by alexal1** [comment]
Well, that's very strange, it should work. The only explanation I got – you have an old Instagram app version, try to update it. By the way, did you change something in the script? Maybe problems occurred after some changes?

**Comment by GeikoHub** [comment]
I have installed instagram on this device just for the bot,
so the last one version, installed about 2days ago.

No changes at all on the script, just ran the version you udapted today (4h ago)
Don't understand too why just don't do nothing and skip every users, strange thing...

 i try with a oneplus7 android 10

**Comment by GeikoHub** [comment]
you're right, works like a charm with the other device...
Is it possible due to android version or something?

I think it's better for everyone to let the bot run on a old phone never in use than the one everyday used monopolized by the bot all day long.
But it will be hard to make compatibility with every old one no?

**Comment by alexal1** [comment]
Actually I've tested on three different devices, not new ones too. Maybe Instagram app has different UI elements ids for different Android versions... I'll try to run it Android 5.0.2 on emulator and let you know here.

**Comment by alexal1** [comment]
Sorry, I've tried to install Instagram app on an emulator with Android 5 but didn't succeed. I want to fix this issue nevertheless, but I'll need your help.

Could you please:
1. Install [uiautomatorviewer](https://developer.android.com/training/testing/ui-automator#ui-automator-viewer)
2. Open somebody's profile on your Android 5 phone
3. Make a screenshot using `uiautomatorviewer` program. It actually makes not a screenshot, but a capture of layout hierarchy.
4. Export this screenshot into xml format and attach here.

Why doing all this?
I want to find out what's the difference in the UI between your phone and others. I we find this out, we will make a fix depending on Android version.

**Comment by GeikoHub** [comment]
Ooook, sooo...
After about 2h trying to launch  uiautomatorviewer,
added path variable etc... just impossible to get the software open...
I saw that it only works with java 8 and i have java 14 but impossible to find where to downgrade and no exe for java 8...
I'm a bit lost i admit!

**Comment by alexal1** [comment]
Jeah, it's a bit tricky. It really works only on Java 8 and earlier. As I understand on Windows you'll have to delete Java and install version 8 from scratch. Maybe this will help https://support.quotemedia.com/support/solutions/articles/13000055272-how-to-downgrade-java-version-windows-user-

**Comment by GeikoHub** [comment]
In fact that's not where i'm the most confortable ;)
I stopped when i saw i need to create an account without any really knowledge of this was really the problem.
You confirm me that is so i'll create it tomorrow to get java 8 and transmit you the report ;)

**Comment by pezzotto** [comment]
Same here, I will try to install the viewer on a vm and export the xml.

**Comment by jonap339** [comment]
@alexal1 , One of my devices has android 5.0.1. It does not actually like. Attached is the uiautomatorviewer screenshot. Please let me know if you need anything else! I don't speak English but I communicate by translator haha

[Screenshot.zip](https://github.com/alexal1/Insomniac/files/4768288/Screenshot.zip)

**Comment by alexal1** [comment]
Thanks @jonap339, I found the problem and made a fix.

@GeikoHub @jonap339 could you please checkout this branch and test if everything works fine?

**Comment by GeikoHub** [comment]
Works like a charm here!
Congratulations!

**Comment by pezzotto** [comment]
> Thanks @jonap339, I found the problem and made a fix.
> 
> @GeikoHub @pezzotto could you please checkout this branch and test if everything works fine?

Sorry but idk how to update the branch? Just git pull ?

**Comment by GeikoHub** [comment]
@pezzotto dl it here ;)
https://github.com/alexal1/Insomniac/tree/no-interaction-bug

**Comment by Foncekar** [comment]
git checkout no-interaction-bug

**Comment by pezzotto** [comment]
Working on 5.0.2
