### ISSUE TITLE
when bot use double click for like he is get error

### ISSUE THREAD

**Issue by bogdan19981305** [alexal1/Insomniac#73]
![image](https://user-images.githubusercontent.com/44820651/88914455-4fc70c80-d26b-11ea-95b1-23e73524f269.png)
![image](https://user-images.githubusercontent.com/44820651/88914497-61101900-d26b-11ea-9802-d2632873409b.png)
if bot use doubleclick for like and post have tagged peoples he is take this error

**Comment by alexal1** [comment]
@bogdan19981305 is it because by first click mentions are shown, and by second click one of them is opened?

**Comment by bogdan19981305** [comment]
@alexal1 Yes that's right

**Comment by alexal1** [comment]
@bogdan19981305 quick solution:
Open action_handle_bloggers.py -> comment lines 244-249 ("#" at start of each line). Or delete them. This will completely remove double clicking and fix your issue.

Or you can wait until I implement the following:
After each double click check whether somebody's profile is opened and go back if it is. Unfortunately I can't see a more elegant solution here.

**Comment by bogdan19981305** [comment]
@alexal1 Thank you very much for your work, the fact is that I had this error literally 1 or 2 times in 10 days, in general, it does not bother me very much, I will wait for an update from you, I just wanted to report this error to improve this utility

**Comment by gvmturl** [comment]
Hello guys is it solved?

**Comment by Ardy000** [comment]
> Unfortunately I can't see a more elegant solution here.

You could increase the double tap speed

**Comment by Fadude** [comment]
Fixed on v3.6.1 (will be releases soon)
