### ISSUE TITLE
Make Bot look at images without giving a like.

### ISSUE THREAD

**Issue by JayCarraway** [alexal1/Insomniac#75]
Hey everybody,

to simulate human behaviour it would be nice to have the bot look at images for a certain amount of time without liking them.

Cheers,
J

**Comment by quintendewilde** [comment]
Second on that and maybe make this a sole function?

To fake more humanisch interactions??



Op do 30 jul. 2020 om 19:08 schreef JayCarraway <notifications@github.com>

**Comment by Fadude** [comment]
Added in version v3.4.0 when using --like-precentage parameter
