### ISSUE TITLE
Fast forward through already interacted users

### ISSUE THREAD

**Issue by Eimuex** [alexal1/Insomniac#78]
Sessions becoming longer and longer due to many interactions already made. For example if user has 300k followers it can take a long time scrolling through already interacted users. Again I do it manually, swipe to the bottom 3 – 4 times until it reach non interacted people. Is there a way to automatize this process, fast forward through already interacted users?

Something like if 3 times reach `need to scroll now` due to `already interacted. Skip` swipe to bottom of the page. 

I’m not a programmer and hope this make sense

**Comment by GeikoHub** [comment]
Don't have the solution but having the same problem and agree for that!
(solved for now by changing the user after 2/3 sessions of 300likes)

**Comment by alexal1** [comment]
> Something like if 3 times reach need to scroll now due to already interacted. Skip swipe to bottom of the page.

What's the bottom of the page? There's no bottom as it's continuously loading more.

**Comment by Eimuex** [comment]
> What's the bottom of the page? There's no bottom as it's continuously loading more.

If you swipe fast enough, indicator on the right side reaches the bottom, pause for a moment and loads new batch of users...at least on my phone.

**Comment by GeikoHub** [comment]
> 
> If you swipe fast enough, indicator on the right side reaches the bottom, pause for a moment and loads new batch of users...at least on my phone.

even worth, when you swipe on the followers list, it makes a loading, and loads the sames accounts as before, so it comes back from nearly begining... so it need to swipe fast but not to scroll as you can makes with a finger....

**Comment by Eimuex** [comment]
I did notice that same users pop up, but again, after 3-4 fresh loads it started to interact with new group, all non-interacted users one after another. Maybe it was random list mixup, dunno, don’t want to mislead you, but it did speed up the sessions.
