### ISSUE TITLE
Gets stuck when trying to interact with private account

### ISSUE THREAD

**Issue by Lisiadito** [alexal1/Insomniac#79]
I've run `python insomniac.py --interact <MYUSERNAME>` and it started working fine until it landed on a private account.
```
[08/06 09:54:38] Back to followers list
[08/06 09:54:41] @SOMEPRIVATEACCOUNT: interact
[08/06 09:54:44] Sleep for 2 seconds
[08/06 09:54:47] Scroll down to see more photos.
```

The script should be able to detect if a account is private and not followed to not even start to find pictures.

**Comment by alexal1** [comment]
Well I didn't find another way of how to distinguish private and public accounts. Lack of scrolling possibility is the best indicator :) Does it bring some inconvenience?

**Comment by muzzol** [comment]
I noticed too that a lot of accounts are private so no posts are shown and a lot of time is lost.

can't profile be parsed in some way to recognize if it's set to private?

**Comment by Fadude** [comment]
Done on v3.2.0, when profile recognized as a private-profile, the bot wont even try to swipe down in order to give it likes.
