### ISSUE TITLE
Running on Android Emulator

### ISSUE THREAD

**Issue by mytraddress** [alexal1/Insomniac#84]
Can this code be run as efficiently on an Android Emulator? Or would that increase the risk of Instagram blocking/shadowbanning the account? Thanks!

**Comment by patrocle** [comment]
I use noox app player with instagram v150 from uptodown (last version has reel not search in bottom menu), it works well.
root on in nox config, debug on in android then connect to the emulator with
`adb connect 127.0.0.1:62001`

**Comment by muzzol** [comment]
I'm running it with official google Android Studio and it works well.

**Comment by DontKnowGuy** [comment]
> I'm running it with official google Android Studio and it works well.

how you runned with android studio? any guide?

**Comment by muzzol** [comment]
> > I'm running it with official google Android Studio and it works well.
> 
> how you runned with android studio? any guide?

I didn't do anything special, where are you stuck?
