### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by shurco** [alexal1/Insomniac#91]
Hi,
after update to version 2
I see error: 
Traceback (most recent call last):
  File "insomniac.py", line 12, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

Tested on Mac 10.15.6 and  Raspberry 4 (dietpi)

**Comment by alexal1** [comment]
Well seems that error is pretty self-descriptive, isn't it?

`pip3 list` to see all installed packages, colorama must be there
`pip3 install colorama` to install

**Comment by shurco** [comment]
```
$ pip3 list
Package         Version
--------------- ---------
adbutils        0.8.1
apkutils2       1.0.0
cached-property 1.5.1
certifi         2020.6.20
chardet         3.0.4
cigam           0.0.3
colorama        0.4.3
decorator       4.4.2
Deprecated      1.2.10
deprecation     2.1.0
idna            2.10
logzero         1.5.0
lxml            4.5.2
packaging       20.4
Pillow          7.2.0
pip             20.1.1
progress        1.5
py              1.9.0
pyelftools      0.26
pyparsing       2.4.7
requests        2.24.0
retry           0.9.2
setuptools      49.2.0
six             1.15.0
uiautomator2    2.11.1
urllib3         1.25.10
wheel           0.34.2
whichcraft      0.6.1
wrapt           1.12.1
xmltodict       0.12.0
```

**Comment by alexal1** [comment]
Try uninstall and install again, better as a superuser:
```
sudo pip3 uninstall colorama
sudo pip3 install colorama
```

All that I can say is that it's an environment problem, not with the script.

**Comment by shurco** [comment]
Did not help.

**Comment by alexal1** [comment]
Ok then maybe this will https://stackoverflow.com/a/4910393/7271660

`python3 -m pip install colorama`

**Comment by shurco** [comment]
Nice!!! It's work!
Thank
