### ISSUE TITLE
FEATURE - Switch between accounts after the end of a session.

### ISSUE THREAD

**Issue by guztavoalves** [alexal1/Insomniac#98]
It would be very good for productivity purposes to be able to switch between accounts at the IG after the end of a session.

Example

--switch account1 account5 account2 account4  account3 

After finishing the session on 'account1' switches to the next on the list, 'account5' and so on ...

![chrome_rafDPBjDwE](https://user-images.githubusercontent.com/11070237/91893541-a9579800-ec6a-11ea-8eff-c4220d3adda1.png)

**Comment by Fadude** [comment]
Added on v3.6.0. Closing.
